// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/accountgroup"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/announcementread"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/asyncmediatask"
	"github.com/Wei-Shaw/sub2api/ent/asyncvideotask"
	"github.com/Wei-Shaw/sub2api/ent/authidentity"
	"github.com/Wei-Shaw/sub2api/ent/authidentitychannel"
	"github.com/Wei-Shaw/sub2api/ent/balanceledger"
	"github.com/Wei-Shaw/sub2api/ent/batchimageevent"
	"github.com/Wei-Shaw/sub2api/ent/batchimageitem"
	"github.com/Wei-Shaw/sub2api/ent/batchimagejob"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitor"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitordailyrollup"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorhistory"
	"github.com/Wei-Shaw/sub2api/ent/channelmonitorrequesttemplate"
	"github.com/Wei-Shaw/sub2api/ent/companyupgradeapplication"
	"github.com/Wei-Shaw/sub2api/ent/compositemodelroute"
	"github.com/Wei-Shaw/sub2api/ent/developerkey"
	"github.com/Wei-Shaw/sub2api/ent/errorpassthroughrule"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/idempotencyrecord"
	"github.com/Wei-Shaw/sub2api/ent/identityadoptiondecision"
	"github.com/Wei-Shaw/sub2api/ent/innerapiapp"
	"github.com/Wei-Shaw/sub2api/ent/managedpolicy"
	"github.com/Wei-Shaw/sub2api/ent/managedpolicyaction"
	"github.com/Wei-Shaw/sub2api/ent/memberpolicyattachment"
	"github.com/Wei-Shaw/sub2api/ent/notificationoutbox"
	"github.com/Wei-Shaw/sub2api/ent/oidcaccesstoken"
	"github.com/Wei-Shaw/sub2api/ent/oidcauthorizationcode"
	"github.com/Wei-Shaw/sub2api/ent/oidcclient"
	"github.com/Wei-Shaw/sub2api/ent/oidcconsent"
	"github.com/Wei-Shaw/sub2api/ent/oidcrefreshtoken"
	"github.com/Wei-Shaw/sub2api/ent/organization"
	"github.com/Wei-Shaw/sub2api/ent/organizationauditevent"
	"github.com/Wei-Shaw/sub2api/ent/organizationfinancialledger"
	"github.com/Wei-Shaw/sub2api/ent/organizationmembership"
	"github.com/Wei-Shaw/sub2api/ent/organizationmemberspendlimit"
	"github.com/Wei-Shaw/sub2api/ent/organizationnamechangerequest"
	"github.com/Wei-Shaw/sub2api/ent/paymentauditlog"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentproviderinstance"
	"github.com/Wei-Shaw/sub2api/ent/pendingauthsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promocode"
	"github.com/Wei-Shaw/sub2api/ent/promocodeusage"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/securitysecret"
	"github.com/Wei-Shaw/sub2api/ent/setting"
	"github.com/Wei-Shaw/sub2api/ent/ssosession"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionplan"
	"github.com/Wei-Shaw/sub2api/ent/supportchatconversation"
	"github.com/Wei-Shaw/sub2api/ent/supportchatmessage"
	"github.com/Wei-Shaw/sub2api/ent/supportdocchunk"
	"github.com/Wei-Shaw/sub2api/ent/supportfaqitem"
	"github.com/Wei-Shaw/sub2api/ent/supportticket"
	"github.com/Wei-Shaw/sub2api/ent/supportticketnotification"
	"github.com/Wei-Shaw/sub2api/ent/supportticketread"
	"github.com/Wei-Shaw/sub2api/ent/supportticketreply"
	"github.com/Wei-Shaw/sub2api/ent/tlsfingerprintprofile"
	"github.com/Wei-Shaw/sub2api/ent/usagecleanuptask"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userallowedgroup"
	"github.com/Wei-Shaw/sub2api/ent/userattributedefinition"
	"github.com/Wei-Shaw/sub2api/ent/userattributevalue"
	"github.com/Wei-Shaw/sub2api/ent/userplatformquota"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/ent/videopricing"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIKeyFunc func(context.Context, *ent.APIKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f APIKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The TraverseAPIKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIKey func(context.Context, *ent.APIKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.APIKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIKeyQuery", q)
}

// The AccountFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountFunc func(context.Context, *ent.AccountQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountQuery", q)
}

// The TraverseAccount type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccount func(context.Context, *ent.AccountQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccount) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccount) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountQuery", q)
}

// The AccountGroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type AccountGroupFunc func(context.Context, *ent.AccountGroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AccountGroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AccountGroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AccountGroupQuery", q)
}

// The TraverseAccountGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAccountGroup func(context.Context, *ent.AccountGroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAccountGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAccountGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AccountGroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AccountGroupQuery", q)
}

// The AnnouncementFunc type is an adapter to allow the use of ordinary function as a Querier.
type AnnouncementFunc func(context.Context, *ent.AnnouncementQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AnnouncementFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AnnouncementQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementQuery", q)
}

// The TraverseAnnouncement type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAnnouncement func(context.Context, *ent.AnnouncementQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAnnouncement) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAnnouncement) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AnnouncementQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementQuery", q)
}

// The AnnouncementReadFunc type is an adapter to allow the use of ordinary function as a Querier.
type AnnouncementReadFunc func(context.Context, *ent.AnnouncementReadQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AnnouncementReadFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AnnouncementReadQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementReadQuery", q)
}

// The TraverseAnnouncementRead type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAnnouncementRead func(context.Context, *ent.AnnouncementReadQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAnnouncementRead) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAnnouncementRead) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AnnouncementReadQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AnnouncementReadQuery", q)
}

// The AsyncMediaTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type AsyncMediaTaskFunc func(context.Context, *ent.AsyncMediaTaskQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AsyncMediaTaskFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AsyncMediaTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AsyncMediaTaskQuery", q)
}

// The TraverseAsyncMediaTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAsyncMediaTask func(context.Context, *ent.AsyncMediaTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAsyncMediaTask) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAsyncMediaTask) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AsyncMediaTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AsyncMediaTaskQuery", q)
}

// The AsyncVideoTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type AsyncVideoTaskFunc func(context.Context, *ent.AsyncVideoTaskQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AsyncVideoTaskFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AsyncVideoTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AsyncVideoTaskQuery", q)
}

// The TraverseAsyncVideoTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAsyncVideoTask func(context.Context, *ent.AsyncVideoTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAsyncVideoTask) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAsyncVideoTask) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AsyncVideoTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AsyncVideoTaskQuery", q)
}

// The AuthIdentityFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthIdentityFunc func(context.Context, *ent.AuthIdentityQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthIdentityFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthIdentityQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityQuery", q)
}

// The TraverseAuthIdentity type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthIdentity func(context.Context, *ent.AuthIdentityQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthIdentity) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthIdentity) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthIdentityQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityQuery", q)
}

// The AuthIdentityChannelFunc type is an adapter to allow the use of ordinary function as a Querier.
type AuthIdentityChannelFunc func(context.Context, *ent.AuthIdentityChannelQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AuthIdentityChannelFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AuthIdentityChannelQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityChannelQuery", q)
}

// The TraverseAuthIdentityChannel type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAuthIdentityChannel func(context.Context, *ent.AuthIdentityChannelQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAuthIdentityChannel) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAuthIdentityChannel) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AuthIdentityChannelQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AuthIdentityChannelQuery", q)
}

// The BalanceLedgerFunc type is an adapter to allow the use of ordinary function as a Querier.
type BalanceLedgerFunc func(context.Context, *ent.BalanceLedgerQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BalanceLedgerFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BalanceLedgerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BalanceLedgerQuery", q)
}

// The TraverseBalanceLedger type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBalanceLedger func(context.Context, *ent.BalanceLedgerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBalanceLedger) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBalanceLedger) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BalanceLedgerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BalanceLedgerQuery", q)
}

// The BatchImageEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type BatchImageEventFunc func(context.Context, *ent.BatchImageEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BatchImageEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BatchImageEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BatchImageEventQuery", q)
}

// The TraverseBatchImageEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBatchImageEvent func(context.Context, *ent.BatchImageEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBatchImageEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBatchImageEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BatchImageEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BatchImageEventQuery", q)
}

// The BatchImageItemFunc type is an adapter to allow the use of ordinary function as a Querier.
type BatchImageItemFunc func(context.Context, *ent.BatchImageItemQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BatchImageItemFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BatchImageItemQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BatchImageItemQuery", q)
}

// The TraverseBatchImageItem type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBatchImageItem func(context.Context, *ent.BatchImageItemQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBatchImageItem) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBatchImageItem) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BatchImageItemQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BatchImageItemQuery", q)
}

// The BatchImageJobFunc type is an adapter to allow the use of ordinary function as a Querier.
type BatchImageJobFunc func(context.Context, *ent.BatchImageJobQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f BatchImageJobFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.BatchImageJobQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.BatchImageJobQuery", q)
}

// The TraverseBatchImageJob type is an adapter to allow the use of ordinary function as Traverser.
type TraverseBatchImageJob func(context.Context, *ent.BatchImageJobQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseBatchImageJob) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseBatchImageJob) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.BatchImageJobQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.BatchImageJobQuery", q)
}

// The ChannelMonitorFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorFunc func(context.Context, *ent.ChannelMonitorQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorQuery", q)
}

// The TraverseChannelMonitor type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitor func(context.Context, *ent.ChannelMonitorQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitor) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitor) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorQuery", q)
}

// The ChannelMonitorDailyRollupFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorDailyRollupFunc func(context.Context, *ent.ChannelMonitorDailyRollupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorDailyRollupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorDailyRollupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorDailyRollupQuery", q)
}

// The TraverseChannelMonitorDailyRollup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorDailyRollup func(context.Context, *ent.ChannelMonitorDailyRollupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorDailyRollup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorDailyRollup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorDailyRollupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorDailyRollupQuery", q)
}

// The ChannelMonitorHistoryFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorHistoryFunc func(context.Context, *ent.ChannelMonitorHistoryQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorHistoryFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorHistoryQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorHistoryQuery", q)
}

// The TraverseChannelMonitorHistory type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorHistory func(context.Context, *ent.ChannelMonitorHistoryQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorHistory) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorHistory) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorHistoryQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorHistoryQuery", q)
}

// The ChannelMonitorRequestTemplateFunc type is an adapter to allow the use of ordinary function as a Querier.
type ChannelMonitorRequestTemplateFunc func(context.Context, *ent.ChannelMonitorRequestTemplateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ChannelMonitorRequestTemplateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ChannelMonitorRequestTemplateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorRequestTemplateQuery", q)
}

// The TraverseChannelMonitorRequestTemplate type is an adapter to allow the use of ordinary function as Traverser.
type TraverseChannelMonitorRequestTemplate func(context.Context, *ent.ChannelMonitorRequestTemplateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseChannelMonitorRequestTemplate) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseChannelMonitorRequestTemplate) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ChannelMonitorRequestTemplateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ChannelMonitorRequestTemplateQuery", q)
}

// The CompanyUpgradeApplicationFunc type is an adapter to allow the use of ordinary function as a Querier.
type CompanyUpgradeApplicationFunc func(context.Context, *ent.CompanyUpgradeApplicationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CompanyUpgradeApplicationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CompanyUpgradeApplicationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CompanyUpgradeApplicationQuery", q)
}

// The TraverseCompanyUpgradeApplication type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCompanyUpgradeApplication func(context.Context, *ent.CompanyUpgradeApplicationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCompanyUpgradeApplication) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCompanyUpgradeApplication) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CompanyUpgradeApplicationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CompanyUpgradeApplicationQuery", q)
}

// The CompositeModelRouteFunc type is an adapter to allow the use of ordinary function as a Querier.
type CompositeModelRouteFunc func(context.Context, *ent.CompositeModelRouteQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CompositeModelRouteFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CompositeModelRouteQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CompositeModelRouteQuery", q)
}

// The TraverseCompositeModelRoute type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCompositeModelRoute func(context.Context, *ent.CompositeModelRouteQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCompositeModelRoute) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCompositeModelRoute) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CompositeModelRouteQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CompositeModelRouteQuery", q)
}

// The DeveloperKeyFunc type is an adapter to allow the use of ordinary function as a Querier.
type DeveloperKeyFunc func(context.Context, *ent.DeveloperKeyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f DeveloperKeyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.DeveloperKeyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.DeveloperKeyQuery", q)
}

// The TraverseDeveloperKey type is an adapter to allow the use of ordinary function as Traverser.
type TraverseDeveloperKey func(context.Context, *ent.DeveloperKeyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseDeveloperKey) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseDeveloperKey) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.DeveloperKeyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.DeveloperKeyQuery", q)
}

// The ErrorPassthroughRuleFunc type is an adapter to allow the use of ordinary function as a Querier.
type ErrorPassthroughRuleFunc func(context.Context, *ent.ErrorPassthroughRuleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ErrorPassthroughRuleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ErrorPassthroughRuleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ErrorPassthroughRuleQuery", q)
}

// The TraverseErrorPassthroughRule type is an adapter to allow the use of ordinary function as Traverser.
type TraverseErrorPassthroughRule func(context.Context, *ent.ErrorPassthroughRuleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseErrorPassthroughRule) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseErrorPassthroughRule) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ErrorPassthroughRuleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ErrorPassthroughRuleQuery", q)
}

// The GroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type GroupFunc func(context.Context, *ent.GroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f GroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.GroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.GroupQuery", q)
}

// The TraverseGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseGroup func(context.Context, *ent.GroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.GroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.GroupQuery", q)
}

// The IdempotencyRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type IdempotencyRecordFunc func(context.Context, *ent.IdempotencyRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f IdempotencyRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.IdempotencyRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.IdempotencyRecordQuery", q)
}

// The TraverseIdempotencyRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseIdempotencyRecord func(context.Context, *ent.IdempotencyRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseIdempotencyRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseIdempotencyRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.IdempotencyRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.IdempotencyRecordQuery", q)
}

// The IdentityAdoptionDecisionFunc type is an adapter to allow the use of ordinary function as a Querier.
type IdentityAdoptionDecisionFunc func(context.Context, *ent.IdentityAdoptionDecisionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f IdentityAdoptionDecisionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.IdentityAdoptionDecisionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.IdentityAdoptionDecisionQuery", q)
}

// The TraverseIdentityAdoptionDecision type is an adapter to allow the use of ordinary function as Traverser.
type TraverseIdentityAdoptionDecision func(context.Context, *ent.IdentityAdoptionDecisionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseIdentityAdoptionDecision) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseIdentityAdoptionDecision) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.IdentityAdoptionDecisionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.IdentityAdoptionDecisionQuery", q)
}

// The InnerAPIAppFunc type is an adapter to allow the use of ordinary function as a Querier.
type InnerAPIAppFunc func(context.Context, *ent.InnerAPIAppQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f InnerAPIAppFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.InnerAPIAppQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.InnerAPIAppQuery", q)
}

// The TraverseInnerAPIApp type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInnerAPIApp func(context.Context, *ent.InnerAPIAppQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInnerAPIApp) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInnerAPIApp) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.InnerAPIAppQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.InnerAPIAppQuery", q)
}

// The ManagedPolicyFunc type is an adapter to allow the use of ordinary function as a Querier.
type ManagedPolicyFunc func(context.Context, *ent.ManagedPolicyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ManagedPolicyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ManagedPolicyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ManagedPolicyQuery", q)
}

// The TraverseManagedPolicy type is an adapter to allow the use of ordinary function as Traverser.
type TraverseManagedPolicy func(context.Context, *ent.ManagedPolicyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseManagedPolicy) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseManagedPolicy) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ManagedPolicyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ManagedPolicyQuery", q)
}

// The ManagedPolicyActionFunc type is an adapter to allow the use of ordinary function as a Querier.
type ManagedPolicyActionFunc func(context.Context, *ent.ManagedPolicyActionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ManagedPolicyActionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ManagedPolicyActionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ManagedPolicyActionQuery", q)
}

// The TraverseManagedPolicyAction type is an adapter to allow the use of ordinary function as Traverser.
type TraverseManagedPolicyAction func(context.Context, *ent.ManagedPolicyActionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseManagedPolicyAction) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseManagedPolicyAction) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ManagedPolicyActionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ManagedPolicyActionQuery", q)
}

// The MemberPolicyAttachmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type MemberPolicyAttachmentFunc func(context.Context, *ent.MemberPolicyAttachmentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f MemberPolicyAttachmentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.MemberPolicyAttachmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.MemberPolicyAttachmentQuery", q)
}

// The TraverseMemberPolicyAttachment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseMemberPolicyAttachment func(context.Context, *ent.MemberPolicyAttachmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseMemberPolicyAttachment) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseMemberPolicyAttachment) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.MemberPolicyAttachmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.MemberPolicyAttachmentQuery", q)
}

// The NotificationOutboxFunc type is an adapter to allow the use of ordinary function as a Querier.
type NotificationOutboxFunc func(context.Context, *ent.NotificationOutboxQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f NotificationOutboxFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.NotificationOutboxQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.NotificationOutboxQuery", q)
}

// The TraverseNotificationOutbox type is an adapter to allow the use of ordinary function as Traverser.
type TraverseNotificationOutbox func(context.Context, *ent.NotificationOutboxQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseNotificationOutbox) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseNotificationOutbox) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.NotificationOutboxQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.NotificationOutboxQuery", q)
}

// The OidcAccessTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type OidcAccessTokenFunc func(context.Context, *ent.OidcAccessTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OidcAccessTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OidcAccessTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OidcAccessTokenQuery", q)
}

// The TraverseOidcAccessToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOidcAccessToken func(context.Context, *ent.OidcAccessTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOidcAccessToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOidcAccessToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OidcAccessTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OidcAccessTokenQuery", q)
}

// The OidcAuthorizationCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type OidcAuthorizationCodeFunc func(context.Context, *ent.OidcAuthorizationCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OidcAuthorizationCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OidcAuthorizationCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OidcAuthorizationCodeQuery", q)
}

// The TraverseOidcAuthorizationCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOidcAuthorizationCode func(context.Context, *ent.OidcAuthorizationCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOidcAuthorizationCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOidcAuthorizationCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OidcAuthorizationCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OidcAuthorizationCodeQuery", q)
}

// The OidcClientFunc type is an adapter to allow the use of ordinary function as a Querier.
type OidcClientFunc func(context.Context, *ent.OidcClientQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OidcClientFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OidcClientQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OidcClientQuery", q)
}

// The TraverseOidcClient type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOidcClient func(context.Context, *ent.OidcClientQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOidcClient) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOidcClient) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OidcClientQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OidcClientQuery", q)
}

// The OidcConsentFunc type is an adapter to allow the use of ordinary function as a Querier.
type OidcConsentFunc func(context.Context, *ent.OidcConsentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OidcConsentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OidcConsentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OidcConsentQuery", q)
}

// The TraverseOidcConsent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOidcConsent func(context.Context, *ent.OidcConsentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOidcConsent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOidcConsent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OidcConsentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OidcConsentQuery", q)
}

// The OidcRefreshTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type OidcRefreshTokenFunc func(context.Context, *ent.OidcRefreshTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OidcRefreshTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OidcRefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OidcRefreshTokenQuery", q)
}

// The TraverseOidcRefreshToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOidcRefreshToken func(context.Context, *ent.OidcRefreshTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOidcRefreshToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOidcRefreshToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OidcRefreshTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OidcRefreshTokenQuery", q)
}

// The OrganizationFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationFunc func(context.Context, *ent.OrganizationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationQuery", q)
}

// The TraverseOrganization type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganization func(context.Context, *ent.OrganizationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganization) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganization) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationQuery", q)
}

// The OrganizationAuditEventFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationAuditEventFunc func(context.Context, *ent.OrganizationAuditEventQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationAuditEventFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationAuditEventQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationAuditEventQuery", q)
}

// The TraverseOrganizationAuditEvent type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganizationAuditEvent func(context.Context, *ent.OrganizationAuditEventQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganizationAuditEvent) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganizationAuditEvent) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationAuditEventQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationAuditEventQuery", q)
}

// The OrganizationFinancialLedgerFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationFinancialLedgerFunc func(context.Context, *ent.OrganizationFinancialLedgerQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationFinancialLedgerFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationFinancialLedgerQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationFinancialLedgerQuery", q)
}

// The TraverseOrganizationFinancialLedger type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganizationFinancialLedger func(context.Context, *ent.OrganizationFinancialLedgerQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganizationFinancialLedger) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganizationFinancialLedger) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationFinancialLedgerQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationFinancialLedgerQuery", q)
}

// The OrganizationMemberSpendLimitFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationMemberSpendLimitFunc func(context.Context, *ent.OrganizationMemberSpendLimitQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationMemberSpendLimitFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationMemberSpendLimitQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationMemberSpendLimitQuery", q)
}

// The TraverseOrganizationMemberSpendLimit type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganizationMemberSpendLimit func(context.Context, *ent.OrganizationMemberSpendLimitQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganizationMemberSpendLimit) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganizationMemberSpendLimit) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationMemberSpendLimitQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationMemberSpendLimitQuery", q)
}

// The OrganizationMembershipFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationMembershipFunc func(context.Context, *ent.OrganizationMembershipQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationMembershipFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationMembershipQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationMembershipQuery", q)
}

// The TraverseOrganizationMembership type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganizationMembership func(context.Context, *ent.OrganizationMembershipQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganizationMembership) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganizationMembership) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationMembershipQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationMembershipQuery", q)
}

// The OrganizationNameChangeRequestFunc type is an adapter to allow the use of ordinary function as a Querier.
type OrganizationNameChangeRequestFunc func(context.Context, *ent.OrganizationNameChangeRequestQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OrganizationNameChangeRequestFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OrganizationNameChangeRequestQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OrganizationNameChangeRequestQuery", q)
}

// The TraverseOrganizationNameChangeRequest type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOrganizationNameChangeRequest func(context.Context, *ent.OrganizationNameChangeRequestQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOrganizationNameChangeRequest) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOrganizationNameChangeRequest) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OrganizationNameChangeRequestQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OrganizationNameChangeRequestQuery", q)
}

// The PaymentAuditLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentAuditLogFunc func(context.Context, *ent.PaymentAuditLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentAuditLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentAuditLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentAuditLogQuery", q)
}

// The TraversePaymentAuditLog type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentAuditLog func(context.Context, *ent.PaymentAuditLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentAuditLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentAuditLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentAuditLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentAuditLogQuery", q)
}

// The PaymentOrderFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentOrderFunc func(context.Context, *ent.PaymentOrderQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentOrderFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentOrderQuery", q)
}

// The TraversePaymentOrder type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentOrder func(context.Context, *ent.PaymentOrderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentOrder) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentOrder) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentOrderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentOrderQuery", q)
}

// The PaymentProviderInstanceFunc type is an adapter to allow the use of ordinary function as a Querier.
type PaymentProviderInstanceFunc func(context.Context, *ent.PaymentProviderInstanceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PaymentProviderInstanceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PaymentProviderInstanceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderInstanceQuery", q)
}

// The TraversePaymentProviderInstance type is an adapter to allow the use of ordinary function as Traverser.
type TraversePaymentProviderInstance func(context.Context, *ent.PaymentProviderInstanceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePaymentProviderInstance) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePaymentProviderInstance) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PaymentProviderInstanceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PaymentProviderInstanceQuery", q)
}

// The PendingAuthSessionFunc type is an adapter to allow the use of ordinary function as a Querier.
type PendingAuthSessionFunc func(context.Context, *ent.PendingAuthSessionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PendingAuthSessionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PendingAuthSessionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PendingAuthSessionQuery", q)
}

// The TraversePendingAuthSession type is an adapter to allow the use of ordinary function as Traverser.
type TraversePendingAuthSession func(context.Context, *ent.PendingAuthSessionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePendingAuthSession) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePendingAuthSession) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PendingAuthSessionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PendingAuthSessionQuery", q)
}

// The PromoCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type PromoCodeFunc func(context.Context, *ent.PromoCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PromoCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PromoCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeQuery", q)
}

// The TraversePromoCode type is an adapter to allow the use of ordinary function as Traverser.
type TraversePromoCode func(context.Context, *ent.PromoCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePromoCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePromoCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PromoCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeQuery", q)
}

// The PromoCodeUsageFunc type is an adapter to allow the use of ordinary function as a Querier.
type PromoCodeUsageFunc func(context.Context, *ent.PromoCodeUsageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PromoCodeUsageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PromoCodeUsageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeUsageQuery", q)
}

// The TraversePromoCodeUsage type is an adapter to allow the use of ordinary function as Traverser.
type TraversePromoCodeUsage func(context.Context, *ent.PromoCodeUsageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePromoCodeUsage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePromoCodeUsage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PromoCodeUsageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PromoCodeUsageQuery", q)
}

// The ProxyFunc type is an adapter to allow the use of ordinary function as a Querier.
type ProxyFunc func(context.Context, *ent.ProxyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ProxyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ProxyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ProxyQuery", q)
}

// The TraverseProxy type is an adapter to allow the use of ordinary function as Traverser.
type TraverseProxy func(context.Context, *ent.ProxyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseProxy) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseProxy) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ProxyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ProxyQuery", q)
}

// The RedeemCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type RedeemCodeFunc func(context.Context, *ent.RedeemCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RedeemCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RedeemCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RedeemCodeQuery", q)
}

// The TraverseRedeemCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRedeemCode func(context.Context, *ent.RedeemCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRedeemCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRedeemCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RedeemCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RedeemCodeQuery", q)
}

// The SecuritySecretFunc type is an adapter to allow the use of ordinary function as a Querier.
type SecuritySecretFunc func(context.Context, *ent.SecuritySecretQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SecuritySecretFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SecuritySecretQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SecuritySecretQuery", q)
}

// The TraverseSecuritySecret type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSecuritySecret func(context.Context, *ent.SecuritySecretQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSecuritySecret) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSecuritySecret) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SecuritySecretQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SecuritySecretQuery", q)
}

// The SettingFunc type is an adapter to allow the use of ordinary function as a Querier.
type SettingFunc func(context.Context, *ent.SettingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SettingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The TraverseSetting type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSetting func(context.Context, *ent.SettingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSetting) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSetting) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SettingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SettingQuery", q)
}

// The SsoSessionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SsoSessionFunc func(context.Context, *ent.SsoSessionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SsoSessionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SsoSessionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SsoSessionQuery", q)
}

// The TraverseSsoSession type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSsoSession func(context.Context, *ent.SsoSessionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSsoSession) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSsoSession) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SsoSessionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SsoSessionQuery", q)
}

// The SubscriptionPlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriptionPlanFunc func(context.Context, *ent.SubscriptionPlanQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubscriptionPlanFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubscriptionPlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionPlanQuery", q)
}

// The TraverseSubscriptionPlan type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscriptionPlan func(context.Context, *ent.SubscriptionPlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscriptionPlan) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscriptionPlan) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubscriptionPlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubscriptionPlanQuery", q)
}

// The SupportChatConversationFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportChatConversationFunc func(context.Context, *ent.SupportChatConversationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportChatConversationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportChatConversationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportChatConversationQuery", q)
}

// The TraverseSupportChatConversation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportChatConversation func(context.Context, *ent.SupportChatConversationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportChatConversation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportChatConversation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportChatConversationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportChatConversationQuery", q)
}

// The SupportChatMessageFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportChatMessageFunc func(context.Context, *ent.SupportChatMessageQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportChatMessageFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportChatMessageQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportChatMessageQuery", q)
}

// The TraverseSupportChatMessage type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportChatMessage func(context.Context, *ent.SupportChatMessageQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportChatMessage) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportChatMessage) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportChatMessageQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportChatMessageQuery", q)
}

// The SupportDocChunkFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportDocChunkFunc func(context.Context, *ent.SupportDocChunkQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportDocChunkFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportDocChunkQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportDocChunkQuery", q)
}

// The TraverseSupportDocChunk type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportDocChunk func(context.Context, *ent.SupportDocChunkQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportDocChunk) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportDocChunk) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportDocChunkQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportDocChunkQuery", q)
}

// The SupportFaqItemFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportFaqItemFunc func(context.Context, *ent.SupportFaqItemQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportFaqItemFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportFaqItemQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportFaqItemQuery", q)
}

// The TraverseSupportFaqItem type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportFaqItem func(context.Context, *ent.SupportFaqItemQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportFaqItem) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportFaqItem) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportFaqItemQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportFaqItemQuery", q)
}

// The SupportTicketFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportTicketFunc func(context.Context, *ent.SupportTicketQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportTicketFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportTicketQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketQuery", q)
}

// The TraverseSupportTicket type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportTicket func(context.Context, *ent.SupportTicketQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportTicket) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportTicket) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportTicketQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketQuery", q)
}

// The SupportTicketNotificationFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportTicketNotificationFunc func(context.Context, *ent.SupportTicketNotificationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportTicketNotificationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportTicketNotificationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketNotificationQuery", q)
}

// The TraverseSupportTicketNotification type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportTicketNotification func(context.Context, *ent.SupportTicketNotificationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportTicketNotification) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportTicketNotification) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportTicketNotificationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketNotificationQuery", q)
}

// The SupportTicketReadFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportTicketReadFunc func(context.Context, *ent.SupportTicketReadQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportTicketReadFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportTicketReadQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketReadQuery", q)
}

// The TraverseSupportTicketRead type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportTicketRead func(context.Context, *ent.SupportTicketReadQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportTicketRead) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportTicketRead) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportTicketReadQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketReadQuery", q)
}

// The SupportTicketReplyFunc type is an adapter to allow the use of ordinary function as a Querier.
type SupportTicketReplyFunc func(context.Context, *ent.SupportTicketReplyQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SupportTicketReplyFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SupportTicketReplyQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketReplyQuery", q)
}

// The TraverseSupportTicketReply type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSupportTicketReply func(context.Context, *ent.SupportTicketReplyQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSupportTicketReply) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSupportTicketReply) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SupportTicketReplyQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SupportTicketReplyQuery", q)
}

// The TLSFingerprintProfileFunc type is an adapter to allow the use of ordinary function as a Querier.
type TLSFingerprintProfileFunc func(context.Context, *ent.TLSFingerprintProfileQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f TLSFingerprintProfileFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.TLSFingerprintProfileQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.TLSFingerprintProfileQuery", q)
}

// The TraverseTLSFingerprintProfile type is an adapter to allow the use of ordinary function as Traverser.
type TraverseTLSFingerprintProfile func(context.Context, *ent.TLSFingerprintProfileQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseTLSFingerprintProfile) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseTLSFingerprintProfile) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.TLSFingerprintProfileQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.TLSFingerprintProfileQuery", q)
}

// The UsageCleanupTaskFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageCleanupTaskFunc func(context.Context, *ent.UsageCleanupTaskQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageCleanupTaskFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageCleanupTaskQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageCleanupTaskQuery", q)
}

// The TraverseUsageCleanupTask type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageCleanupTask func(context.Context, *ent.UsageCleanupTaskQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageCleanupTask) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageCleanupTask) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageCleanupTaskQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageCleanupTaskQuery", q)
}

// The UsageLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type UsageLogFunc func(context.Context, *ent.UsageLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UsageLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The TraverseUsageLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUsageLog func(context.Context, *ent.UsageLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUsageLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUsageLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UsageLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UsageLogQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserAllowedGroupFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAllowedGroupFunc func(context.Context, *ent.UserAllowedGroupQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAllowedGroupFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAllowedGroupQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAllowedGroupQuery", q)
}

// The TraverseUserAllowedGroup type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAllowedGroup func(context.Context, *ent.UserAllowedGroupQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAllowedGroup) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAllowedGroup) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAllowedGroupQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAllowedGroupQuery", q)
}

// The UserAttributeDefinitionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAttributeDefinitionFunc func(context.Context, *ent.UserAttributeDefinitionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAttributeDefinitionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAttributeDefinitionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeDefinitionQuery", q)
}

// The TraverseUserAttributeDefinition type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAttributeDefinition func(context.Context, *ent.UserAttributeDefinitionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAttributeDefinition) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAttributeDefinition) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAttributeDefinitionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeDefinitionQuery", q)
}

// The UserAttributeValueFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserAttributeValueFunc func(context.Context, *ent.UserAttributeValueQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserAttributeValueFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserAttributeValueQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeValueQuery", q)
}

// The TraverseUserAttributeValue type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserAttributeValue func(context.Context, *ent.UserAttributeValueQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserAttributeValue) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserAttributeValue) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserAttributeValueQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserAttributeValueQuery", q)
}

// The UserPlatformQuotaFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserPlatformQuotaFunc func(context.Context, *ent.UserPlatformQuotaQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserPlatformQuotaFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserPlatformQuotaQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserPlatformQuotaQuery", q)
}

// The TraverseUserPlatformQuota type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserPlatformQuota func(context.Context, *ent.UserPlatformQuotaQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserPlatformQuota) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserPlatformQuota) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserPlatformQuotaQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserPlatformQuotaQuery", q)
}

// The UserSubscriptionFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserSubscriptionFunc func(context.Context, *ent.UserSubscriptionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserSubscriptionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserSubscriptionQuery", q)
}

// The TraverseUserSubscription type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserSubscription func(context.Context, *ent.UserSubscriptionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserSubscription) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserSubscription) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserSubscriptionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserSubscriptionQuery", q)
}

// The VideoPricingFunc type is an adapter to allow the use of ordinary function as a Querier.
type VideoPricingFunc func(context.Context, *ent.VideoPricingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f VideoPricingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.VideoPricingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.VideoPricingQuery", q)
}

// The TraverseVideoPricing type is an adapter to allow the use of ordinary function as Traverser.
type TraverseVideoPricing func(context.Context, *ent.VideoPricingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseVideoPricing) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseVideoPricing) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.VideoPricingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.VideoPricingQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.APIKeyQuery:
		return &query[*ent.APIKeyQuery, predicate.APIKey, apikey.OrderOption]{typ: ent.TypeAPIKey, tq: q}, nil
	case *ent.AccountQuery:
		return &query[*ent.AccountQuery, predicate.Account, account.OrderOption]{typ: ent.TypeAccount, tq: q}, nil
	case *ent.AccountGroupQuery:
		return &query[*ent.AccountGroupQuery, predicate.AccountGroup, accountgroup.OrderOption]{typ: ent.TypeAccountGroup, tq: q}, nil
	case *ent.AnnouncementQuery:
		return &query[*ent.AnnouncementQuery, predicate.Announcement, announcement.OrderOption]{typ: ent.TypeAnnouncement, tq: q}, nil
	case *ent.AnnouncementReadQuery:
		return &query[*ent.AnnouncementReadQuery, predicate.AnnouncementRead, announcementread.OrderOption]{typ: ent.TypeAnnouncementRead, tq: q}, nil
	case *ent.AsyncMediaTaskQuery:
		return &query[*ent.AsyncMediaTaskQuery, predicate.AsyncMediaTask, asyncmediatask.OrderOption]{typ: ent.TypeAsyncMediaTask, tq: q}, nil
	case *ent.AsyncVideoTaskQuery:
		return &query[*ent.AsyncVideoTaskQuery, predicate.AsyncVideoTask, asyncvideotask.OrderOption]{typ: ent.TypeAsyncVideoTask, tq: q}, nil
	case *ent.AuthIdentityQuery:
		return &query[*ent.AuthIdentityQuery, predicate.AuthIdentity, authidentity.OrderOption]{typ: ent.TypeAuthIdentity, tq: q}, nil
	case *ent.AuthIdentityChannelQuery:
		return &query[*ent.AuthIdentityChannelQuery, predicate.AuthIdentityChannel, authidentitychannel.OrderOption]{typ: ent.TypeAuthIdentityChannel, tq: q}, nil
	case *ent.BalanceLedgerQuery:
		return &query[*ent.BalanceLedgerQuery, predicate.BalanceLedger, balanceledger.OrderOption]{typ: ent.TypeBalanceLedger, tq: q}, nil
	case *ent.BatchImageEventQuery:
		return &query[*ent.BatchImageEventQuery, predicate.BatchImageEvent, batchimageevent.OrderOption]{typ: ent.TypeBatchImageEvent, tq: q}, nil
	case *ent.BatchImageItemQuery:
		return &query[*ent.BatchImageItemQuery, predicate.BatchImageItem, batchimageitem.OrderOption]{typ: ent.TypeBatchImageItem, tq: q}, nil
	case *ent.BatchImageJobQuery:
		return &query[*ent.BatchImageJobQuery, predicate.BatchImageJob, batchimagejob.OrderOption]{typ: ent.TypeBatchImageJob, tq: q}, nil
	case *ent.ChannelMonitorQuery:
		return &query[*ent.ChannelMonitorQuery, predicate.ChannelMonitor, channelmonitor.OrderOption]{typ: ent.TypeChannelMonitor, tq: q}, nil
	case *ent.ChannelMonitorDailyRollupQuery:
		return &query[*ent.ChannelMonitorDailyRollupQuery, predicate.ChannelMonitorDailyRollup, channelmonitordailyrollup.OrderOption]{typ: ent.TypeChannelMonitorDailyRollup, tq: q}, nil
	case *ent.ChannelMonitorHistoryQuery:
		return &query[*ent.ChannelMonitorHistoryQuery, predicate.ChannelMonitorHistory, channelmonitorhistory.OrderOption]{typ: ent.TypeChannelMonitorHistory, tq: q}, nil
	case *ent.ChannelMonitorRequestTemplateQuery:
		return &query[*ent.ChannelMonitorRequestTemplateQuery, predicate.ChannelMonitorRequestTemplate, channelmonitorrequesttemplate.OrderOption]{typ: ent.TypeChannelMonitorRequestTemplate, tq: q}, nil
	case *ent.CompanyUpgradeApplicationQuery:
		return &query[*ent.CompanyUpgradeApplicationQuery, predicate.CompanyUpgradeApplication, companyupgradeapplication.OrderOption]{typ: ent.TypeCompanyUpgradeApplication, tq: q}, nil
	case *ent.CompositeModelRouteQuery:
		return &query[*ent.CompositeModelRouteQuery, predicate.CompositeModelRoute, compositemodelroute.OrderOption]{typ: ent.TypeCompositeModelRoute, tq: q}, nil
	case *ent.DeveloperKeyQuery:
		return &query[*ent.DeveloperKeyQuery, predicate.DeveloperKey, developerkey.OrderOption]{typ: ent.TypeDeveloperKey, tq: q}, nil
	case *ent.ErrorPassthroughRuleQuery:
		return &query[*ent.ErrorPassthroughRuleQuery, predicate.ErrorPassthroughRule, errorpassthroughrule.OrderOption]{typ: ent.TypeErrorPassthroughRule, tq: q}, nil
	case *ent.GroupQuery:
		return &query[*ent.GroupQuery, predicate.Group, group.OrderOption]{typ: ent.TypeGroup, tq: q}, nil
	case *ent.IdempotencyRecordQuery:
		return &query[*ent.IdempotencyRecordQuery, predicate.IdempotencyRecord, idempotencyrecord.OrderOption]{typ: ent.TypeIdempotencyRecord, tq: q}, nil
	case *ent.IdentityAdoptionDecisionQuery:
		return &query[*ent.IdentityAdoptionDecisionQuery, predicate.IdentityAdoptionDecision, identityadoptiondecision.OrderOption]{typ: ent.TypeIdentityAdoptionDecision, tq: q}, nil
	case *ent.InnerAPIAppQuery:
		return &query[*ent.InnerAPIAppQuery, predicate.InnerAPIApp, innerapiapp.OrderOption]{typ: ent.TypeInnerAPIApp, tq: q}, nil
	case *ent.ManagedPolicyQuery:
		return &query[*ent.ManagedPolicyQuery, predicate.ManagedPolicy, managedpolicy.OrderOption]{typ: ent.TypeManagedPolicy, tq: q}, nil
	case *ent.ManagedPolicyActionQuery:
		return &query[*ent.ManagedPolicyActionQuery, predicate.ManagedPolicyAction, managedpolicyaction.OrderOption]{typ: ent.TypeManagedPolicyAction, tq: q}, nil
	case *ent.MemberPolicyAttachmentQuery:
		return &query[*ent.MemberPolicyAttachmentQuery, predicate.MemberPolicyAttachment, memberpolicyattachment.OrderOption]{typ: ent.TypeMemberPolicyAttachment, tq: q}, nil
	case *ent.NotificationOutboxQuery:
		return &query[*ent.NotificationOutboxQuery, predicate.NotificationOutbox, notificationoutbox.OrderOption]{typ: ent.TypeNotificationOutbox, tq: q}, nil
	case *ent.OidcAccessTokenQuery:
		return &query[*ent.OidcAccessTokenQuery, predicate.OidcAccessToken, oidcaccesstoken.OrderOption]{typ: ent.TypeOidcAccessToken, tq: q}, nil
	case *ent.OidcAuthorizationCodeQuery:
		return &query[*ent.OidcAuthorizationCodeQuery, predicate.OidcAuthorizationCode, oidcauthorizationcode.OrderOption]{typ: ent.TypeOidcAuthorizationCode, tq: q}, nil
	case *ent.OidcClientQuery:
		return &query[*ent.OidcClientQuery, predicate.OidcClient, oidcclient.OrderOption]{typ: ent.TypeOidcClient, tq: q}, nil
	case *ent.OidcConsentQuery:
		return &query[*ent.OidcConsentQuery, predicate.OidcConsent, oidcconsent.OrderOption]{typ: ent.TypeOidcConsent, tq: q}, nil
	case *ent.OidcRefreshTokenQuery:
		return &query[*ent.OidcRefreshTokenQuery, predicate.OidcRefreshToken, oidcrefreshtoken.OrderOption]{typ: ent.TypeOidcRefreshToken, tq: q}, nil
	case *ent.OrganizationQuery:
		return &query[*ent.OrganizationQuery, predicate.Organization, organization.OrderOption]{typ: ent.TypeOrganization, tq: q}, nil
	case *ent.OrganizationAuditEventQuery:
		return &query[*ent.OrganizationAuditEventQuery, predicate.OrganizationAuditEvent, organizationauditevent.OrderOption]{typ: ent.TypeOrganizationAuditEvent, tq: q}, nil
	case *ent.OrganizationFinancialLedgerQuery:
		return &query[*ent.OrganizationFinancialLedgerQuery, predicate.OrganizationFinancialLedger, organizationfinancialledger.OrderOption]{typ: ent.TypeOrganizationFinancialLedger, tq: q}, nil
	case *ent.OrganizationMemberSpendLimitQuery:
		return &query[*ent.OrganizationMemberSpendLimitQuery, predicate.OrganizationMemberSpendLimit, organizationmemberspendlimit.OrderOption]{typ: ent.TypeOrganizationMemberSpendLimit, tq: q}, nil
	case *ent.OrganizationMembershipQuery:
		return &query[*ent.OrganizationMembershipQuery, predicate.OrganizationMembership, organizationmembership.OrderOption]{typ: ent.TypeOrganizationMembership, tq: q}, nil
	case *ent.OrganizationNameChangeRequestQuery:
		return &query[*ent.OrganizationNameChangeRequestQuery, predicate.OrganizationNameChangeRequest, organizationnamechangerequest.OrderOption]{typ: ent.TypeOrganizationNameChangeRequest, tq: q}, nil
	case *ent.PaymentAuditLogQuery:
		return &query[*ent.PaymentAuditLogQuery, predicate.PaymentAuditLog, paymentauditlog.OrderOption]{typ: ent.TypePaymentAuditLog, tq: q}, nil
	case *ent.PaymentOrderQuery:
		return &query[*ent.PaymentOrderQuery, predicate.PaymentOrder, paymentorder.OrderOption]{typ: ent.TypePaymentOrder, tq: q}, nil
	case *ent.PaymentProviderInstanceQuery:
		return &query[*ent.PaymentProviderInstanceQuery, predicate.PaymentProviderInstance, paymentproviderinstance.OrderOption]{typ: ent.TypePaymentProviderInstance, tq: q}, nil
	case *ent.PendingAuthSessionQuery:
		return &query[*ent.PendingAuthSessionQuery, predicate.PendingAuthSession, pendingauthsession.OrderOption]{typ: ent.TypePendingAuthSession, tq: q}, nil
	case *ent.PromoCodeQuery:
		return &query[*ent.PromoCodeQuery, predicate.PromoCode, promocode.OrderOption]{typ: ent.TypePromoCode, tq: q}, nil
	case *ent.PromoCodeUsageQuery:
		return &query[*ent.PromoCodeUsageQuery, predicate.PromoCodeUsage, promocodeusage.OrderOption]{typ: ent.TypePromoCodeUsage, tq: q}, nil
	case *ent.ProxyQuery:
		return &query[*ent.ProxyQuery, predicate.Proxy, proxy.OrderOption]{typ: ent.TypeProxy, tq: q}, nil
	case *ent.RedeemCodeQuery:
		return &query[*ent.RedeemCodeQuery, predicate.RedeemCode, redeemcode.OrderOption]{typ: ent.TypeRedeemCode, tq: q}, nil
	case *ent.SecuritySecretQuery:
		return &query[*ent.SecuritySecretQuery, predicate.SecuritySecret, securitysecret.OrderOption]{typ: ent.TypeSecuritySecret, tq: q}, nil
	case *ent.SettingQuery:
		return &query[*ent.SettingQuery, predicate.Setting, setting.OrderOption]{typ: ent.TypeSetting, tq: q}, nil
	case *ent.SsoSessionQuery:
		return &query[*ent.SsoSessionQuery, predicate.SsoSession, ssosession.OrderOption]{typ: ent.TypeSsoSession, tq: q}, nil
	case *ent.SubscriptionPlanQuery:
		return &query[*ent.SubscriptionPlanQuery, predicate.SubscriptionPlan, subscriptionplan.OrderOption]{typ: ent.TypeSubscriptionPlan, tq: q}, nil
	case *ent.SupportChatConversationQuery:
		return &query[*ent.SupportChatConversationQuery, predicate.SupportChatConversation, supportchatconversation.OrderOption]{typ: ent.TypeSupportChatConversation, tq: q}, nil
	case *ent.SupportChatMessageQuery:
		return &query[*ent.SupportChatMessageQuery, predicate.SupportChatMessage, supportchatmessage.OrderOption]{typ: ent.TypeSupportChatMessage, tq: q}, nil
	case *ent.SupportDocChunkQuery:
		return &query[*ent.SupportDocChunkQuery, predicate.SupportDocChunk, supportdocchunk.OrderOption]{typ: ent.TypeSupportDocChunk, tq: q}, nil
	case *ent.SupportFaqItemQuery:
		return &query[*ent.SupportFaqItemQuery, predicate.SupportFaqItem, supportfaqitem.OrderOption]{typ: ent.TypeSupportFaqItem, tq: q}, nil
	case *ent.SupportTicketQuery:
		return &query[*ent.SupportTicketQuery, predicate.SupportTicket, supportticket.OrderOption]{typ: ent.TypeSupportTicket, tq: q}, nil
	case *ent.SupportTicketNotificationQuery:
		return &query[*ent.SupportTicketNotificationQuery, predicate.SupportTicketNotification, supportticketnotification.OrderOption]{typ: ent.TypeSupportTicketNotification, tq: q}, nil
	case *ent.SupportTicketReadQuery:
		return &query[*ent.SupportTicketReadQuery, predicate.SupportTicketRead, supportticketread.OrderOption]{typ: ent.TypeSupportTicketRead, tq: q}, nil
	case *ent.SupportTicketReplyQuery:
		return &query[*ent.SupportTicketReplyQuery, predicate.SupportTicketReply, supportticketreply.OrderOption]{typ: ent.TypeSupportTicketReply, tq: q}, nil
	case *ent.TLSFingerprintProfileQuery:
		return &query[*ent.TLSFingerprintProfileQuery, predicate.TLSFingerprintProfile, tlsfingerprintprofile.OrderOption]{typ: ent.TypeTLSFingerprintProfile, tq: q}, nil
	case *ent.UsageCleanupTaskQuery:
		return &query[*ent.UsageCleanupTaskQuery, predicate.UsageCleanupTask, usagecleanuptask.OrderOption]{typ: ent.TypeUsageCleanupTask, tq: q}, nil
	case *ent.UsageLogQuery:
		return &query[*ent.UsageLogQuery, predicate.UsageLog, usagelog.OrderOption]{typ: ent.TypeUsageLog, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserAllowedGroupQuery:
		return &query[*ent.UserAllowedGroupQuery, predicate.UserAllowedGroup, userallowedgroup.OrderOption]{typ: ent.TypeUserAllowedGroup, tq: q}, nil
	case *ent.UserAttributeDefinitionQuery:
		return &query[*ent.UserAttributeDefinitionQuery, predicate.UserAttributeDefinition, userattributedefinition.OrderOption]{typ: ent.TypeUserAttributeDefinition, tq: q}, nil
	case *ent.UserAttributeValueQuery:
		return &query[*ent.UserAttributeValueQuery, predicate.UserAttributeValue, userattributevalue.OrderOption]{typ: ent.TypeUserAttributeValue, tq: q}, nil
	case *ent.UserPlatformQuotaQuery:
		return &query[*ent.UserPlatformQuotaQuery, predicate.UserPlatformQuota, userplatformquota.OrderOption]{typ: ent.TypeUserPlatformQuota, tq: q}, nil
	case *ent.UserSubscriptionQuery:
		return &query[*ent.UserSubscriptionQuery, predicate.UserSubscription, usersubscription.OrderOption]{typ: ent.TypeUserSubscription, tq: q}, nil
	case *ent.VideoPricingQuery:
		return &query[*ent.VideoPricingQuery, predicate.VideoPricing, videopricing.OrderOption]{typ: ent.TypeVideoPricing, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
