// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/asyncmediatask"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AsyncMediaTaskUpdate is the builder for updating AsyncMediaTask entities.
type AsyncMediaTaskUpdate struct {
	config
	hooks    []Hook
	mutation *AsyncMediaTaskMutation
}

// Where appends a list predicates to the AsyncMediaTaskUpdate builder.
func (_u *AsyncMediaTaskUpdate) Where(ps ...predicate.AsyncMediaTask) *AsyncMediaTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AsyncMediaTaskUpdate) SetUpdatedAt(v time.Time) *AsyncMediaTaskUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInternalRequestID sets the "internal_request_id" field.
func (_u *AsyncMediaTaskUpdate) SetInternalRequestID(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetInternalRequestID(v)
	return _u
}

// SetNillableInternalRequestID sets the "internal_request_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableInternalRequestID(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetInternalRequestID(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *AsyncMediaTaskUpdate) SetUpstreamRequestID(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableUpstreamRequestID(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *AsyncMediaTaskUpdate) ClearUpstreamRequestID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetStatusURL sets the "status_url" field.
func (_u *AsyncMediaTaskUpdate) SetStatusURL(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetStatusURL(v)
	return _u
}

// SetNillableStatusURL sets the "status_url" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableStatusURL(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetStatusURL(*v)
	}
	return _u
}

// ClearStatusURL clears the value of the "status_url" field.
func (_u *AsyncMediaTaskUpdate) ClearStatusURL() *AsyncMediaTaskUpdate {
	_u.mutation.ClearStatusURL()
	return _u
}

// SetResponseURL sets the "response_url" field.
func (_u *AsyncMediaTaskUpdate) SetResponseURL(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetResponseURL(v)
	return _u
}

// SetNillableResponseURL sets the "response_url" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableResponseURL(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetResponseURL(*v)
	}
	return _u
}

// ClearResponseURL clears the value of the "response_url" field.
func (_u *AsyncMediaTaskUpdate) ClearResponseURL() *AsyncMediaTaskUpdate {
	_u.mutation.ClearResponseURL()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AsyncMediaTaskUpdate) SetAccountID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableAccountID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AsyncMediaTaskUpdate) AddAccountID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *AsyncMediaTaskUpdate) ClearAccountID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearAccountID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AsyncMediaTaskUpdate) SetAPIKeyID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableAPIKeyID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AsyncMediaTaskUpdate) AddAPIKeyID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AsyncMediaTaskUpdate) SetUserID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableUserID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AsyncMediaTaskUpdate) AddUserID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *AsyncMediaTaskUpdate) SetOrganizationID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetOrganizationID()
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableOrganizationID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// AddOrganizationID adds value to the "organization_id" field.
func (_u *AsyncMediaTaskUpdate) AddOrganizationID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddOrganizationID(v)
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *AsyncMediaTaskUpdate) ClearOrganizationID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetPayerUserID sets the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdate) SetPayerUserID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetPayerUserID()
	_u.mutation.SetPayerUserID(v)
	return _u
}

// SetNillablePayerUserID sets the "payer_user_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillablePayerUserID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetPayerUserID(*v)
	}
	return _u
}

// AddPayerUserID adds value to the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdate) AddPayerUserID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddPayerUserID(v)
	return _u
}

// ClearPayerUserID clears the value of the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdate) ClearPayerUserID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearPayerUserID()
	return _u
}

// SetBalanceSource sets the "balance_source" field.
func (_u *AsyncMediaTaskUpdate) SetBalanceSource(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetBalanceSource(v)
	return _u
}

// SetNillableBalanceSource sets the "balance_source" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableBalanceSource(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetBalanceSource(*v)
	}
	return _u
}

// ClearBalanceSource clears the value of the "balance_source" field.
func (_u *AsyncMediaTaskUpdate) ClearBalanceSource() *AsyncMediaTaskUpdate {
	_u.mutation.ClearBalanceSource()
	return _u
}

// SetAuthzGeneration sets the "authz_generation" field.
func (_u *AsyncMediaTaskUpdate) SetAuthzGeneration(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetAuthzGeneration()
	_u.mutation.SetAuthzGeneration(v)
	return _u
}

// SetNillableAuthzGeneration sets the "authz_generation" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableAuthzGeneration(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetAuthzGeneration(*v)
	}
	return _u
}

// AddAuthzGeneration adds value to the "authz_generation" field.
func (_u *AsyncMediaTaskUpdate) AddAuthzGeneration(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddAuthzGeneration(v)
	return _u
}

// ClearAuthzGeneration clears the value of the "authz_generation" field.
func (_u *AsyncMediaTaskUpdate) ClearAuthzGeneration() *AsyncMediaTaskUpdate {
	_u.mutation.ClearAuthzGeneration()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AsyncMediaTaskUpdate) SetGroupID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableGroupID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AsyncMediaTaskUpdate) AddGroupID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AsyncMediaTaskUpdate) ClearGroupID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *AsyncMediaTaskUpdate) SetChannelID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableChannelID(v *int64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *AsyncMediaTaskUpdate) AddChannelID(v int64) *AsyncMediaTaskUpdate {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *AsyncMediaTaskUpdate) ClearChannelID() *AsyncMediaTaskUpdate {
	_u.mutation.ClearChannelID()
	return _u
}

// SetFacade sets the "facade" field.
func (_u *AsyncMediaTaskUpdate) SetFacade(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetFacade(v)
	return _u
}

// SetNillableFacade sets the "facade" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableFacade(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetFacade(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *AsyncMediaTaskUpdate) SetRequestedModel(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableRequestedModel(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *AsyncMediaTaskUpdate) SetUpstreamModel(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableUpstreamModel(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *AsyncMediaTaskUpdate) ClearUpstreamModel() *AsyncMediaTaskUpdate {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *AsyncMediaTaskUpdate) SetImageSize(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableImageSize(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// ClearImageSize clears the value of the "image_size" field.
func (_u *AsyncMediaTaskUpdate) ClearImageSize() *AsyncMediaTaskUpdate {
	_u.mutation.ClearImageSize()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *AsyncMediaTaskUpdate) SetQuality(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableQuality(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *AsyncMediaTaskUpdate) ClearQuality() *AsyncMediaTaskUpdate {
	_u.mutation.ClearQuality()
	return _u
}

// SetNumImages sets the "num_images" field.
func (_u *AsyncMediaTaskUpdate) SetNumImages(v int) *AsyncMediaTaskUpdate {
	_u.mutation.ResetNumImages()
	_u.mutation.SetNumImages(v)
	return _u
}

// SetNillableNumImages sets the "num_images" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableNumImages(v *int) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetNumImages(*v)
	}
	return _u
}

// AddNumImages adds value to the "num_images" field.
func (_u *AsyncMediaTaskUpdate) AddNumImages(v int) *AsyncMediaTaskUpdate {
	_u.mutation.AddNumImages(v)
	return _u
}

// SetRequestParameters sets the "request_parameters" field.
func (_u *AsyncMediaTaskUpdate) SetRequestParameters(v map[string]interface{}) *AsyncMediaTaskUpdate {
	_u.mutation.SetRequestParameters(v)
	return _u
}

// ClearRequestParameters clears the value of the "request_parameters" field.
func (_u *AsyncMediaTaskUpdate) ClearRequestParameters() *AsyncMediaTaskUpdate {
	_u.mutation.ClearRequestParameters()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AsyncMediaTaskUpdate) SetStatus(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableStatus(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHeldCost sets the "held_cost" field.
func (_u *AsyncMediaTaskUpdate) SetHeldCost(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetHeldCost()
	_u.mutation.SetHeldCost(v)
	return _u
}

// SetNillableHeldCost sets the "held_cost" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableHeldCost(v *float64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetHeldCost(*v)
	}
	return _u
}

// AddHeldCost adds value to the "held_cost" field.
func (_u *AsyncMediaTaskUpdate) AddHeldCost(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.AddHeldCost(v)
	return _u
}

// SetFinalCost sets the "final_cost" field.
func (_u *AsyncMediaTaskUpdate) SetFinalCost(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetFinalCost()
	_u.mutation.SetFinalCost(v)
	return _u
}

// SetNillableFinalCost sets the "final_cost" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableFinalCost(v *float64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetFinalCost(*v)
	}
	return _u
}

// AddFinalCost adds value to the "final_cost" field.
func (_u *AsyncMediaTaskUpdate) AddFinalCost(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.AddFinalCost(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AsyncMediaTaskUpdate) SetRateMultiplier(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableRateMultiplier(v *float64) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AsyncMediaTaskUpdate) AddRateMultiplier(v float64) *AsyncMediaTaskUpdate {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *AsyncMediaTaskUpdate) SetSizeTier(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableSizeTier(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// ClearSizeTier clears the value of the "size_tier" field.
func (_u *AsyncMediaTaskUpdate) ClearSizeTier() *AsyncMediaTaskUpdate {
	_u.mutation.ClearSizeTier()
	return _u
}

// SetImageUrls sets the "image_urls" field.
func (_u *AsyncMediaTaskUpdate) SetImageUrls(v []string) *AsyncMediaTaskUpdate {
	_u.mutation.SetImageUrls(v)
	return _u
}

// AppendImageUrls appends value to the "image_urls" field.
func (_u *AsyncMediaTaskUpdate) AppendImageUrls(v []string) *AsyncMediaTaskUpdate {
	_u.mutation.AppendImageUrls(v)
	return _u
}

// ClearImageUrls clears the value of the "image_urls" field.
func (_u *AsyncMediaTaskUpdate) ClearImageUrls() *AsyncMediaTaskUpdate {
	_u.mutation.ClearImageUrls()
	return _u
}

// SetCosUrls sets the "cos_urls" field.
func (_u *AsyncMediaTaskUpdate) SetCosUrls(v []string) *AsyncMediaTaskUpdate {
	_u.mutation.SetCosUrls(v)
	return _u
}

// AppendCosUrls appends value to the "cos_urls" field.
func (_u *AsyncMediaTaskUpdate) AppendCosUrls(v []string) *AsyncMediaTaskUpdate {
	_u.mutation.AppendCosUrls(v)
	return _u
}

// ClearCosUrls clears the value of the "cos_urls" field.
func (_u *AsyncMediaTaskUpdate) ClearCosUrls() *AsyncMediaTaskUpdate {
	_u.mutation.ClearCosUrls()
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *AsyncMediaTaskUpdate) SetErrorReason(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableErrorReason(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// ClearErrorReason clears the value of the "error_reason" field.
func (_u *AsyncMediaTaskUpdate) ClearErrorReason() *AsyncMediaTaskUpdate {
	_u.mutation.ClearErrorReason()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AsyncMediaTaskUpdate) SetErrorCode(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableErrorCode(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AsyncMediaTaskUpdate) ClearErrorCode() *AsyncMediaTaskUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetFailDeadlineAt sets the "fail_deadline_at" field.
func (_u *AsyncMediaTaskUpdate) SetFailDeadlineAt(v time.Time) *AsyncMediaTaskUpdate {
	_u.mutation.SetFailDeadlineAt(v)
	return _u
}

// SetNillableFailDeadlineAt sets the "fail_deadline_at" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableFailDeadlineAt(v *time.Time) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetFailDeadlineAt(*v)
	}
	return _u
}

// ClearFailDeadlineAt clears the value of the "fail_deadline_at" field.
func (_u *AsyncMediaTaskUpdate) ClearFailDeadlineAt() *AsyncMediaTaskUpdate {
	_u.mutation.ClearFailDeadlineAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AsyncMediaTaskUpdate) SetFinishedAt(v time.Time) *AsyncMediaTaskUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableFinishedAt(v *time.Time) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AsyncMediaTaskUpdate) ClearFinishedAt() *AsyncMediaTaskUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AsyncMediaTaskUpdate) SetClientIP(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableClientIP(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AsyncMediaTaskUpdate) ClearClientIP() *AsyncMediaTaskUpdate {
	_u.mutation.ClearClientIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AsyncMediaTaskUpdate) SetUserAgent(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableUserAgent(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AsyncMediaTaskUpdate) ClearUserAgent() *AsyncMediaTaskUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_u *AsyncMediaTaskUpdate) SetInboundEndpoint(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetInboundEndpoint(v)
	return _u
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableInboundEndpoint(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetInboundEndpoint(*v)
	}
	return _u
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (_u *AsyncMediaTaskUpdate) ClearInboundEndpoint() *AsyncMediaTaskUpdate {
	_u.mutation.ClearInboundEndpoint()
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *AsyncMediaTaskUpdate) SetUpstreamEndpoint(v string) *AsyncMediaTaskUpdate {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdate) SetNillableUpstreamEndpoint(v *string) *AsyncMediaTaskUpdate {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (_u *AsyncMediaTaskUpdate) ClearUpstreamEndpoint() *AsyncMediaTaskUpdate {
	_u.mutation.ClearUpstreamEndpoint()
	return _u
}

// Mutation returns the AsyncMediaTaskMutation object of the builder.
func (_u *AsyncMediaTaskUpdate) Mutation() *AsyncMediaTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AsyncMediaTaskUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AsyncMediaTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AsyncMediaTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AsyncMediaTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AsyncMediaTaskUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asyncmediatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AsyncMediaTaskUpdate) check() error {
	if v, ok := _u.mutation.InternalRequestID(); ok {
		if err := asyncmediatask.InternalRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "internal_request_id", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.internal_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := asyncmediatask.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusURL(); ok {
		if err := asyncmediatask.StatusURLValidator(v); err != nil {
			return &ValidationError{Name: "status_url", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.status_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseURL(); ok {
		if err := asyncmediatask.ResponseURLValidator(v); err != nil {
			return &ValidationError{Name: "response_url", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.response_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceSource(); ok {
		if err := asyncmediatask.BalanceSourceValidator(v); err != nil {
			return &ValidationError{Name: "balance_source", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.balance_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Facade(); ok {
		if err := asyncmediatask.FacadeValidator(v); err != nil {
			return &ValidationError{Name: "facade", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.facade": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := asyncmediatask.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := asyncmediatask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := asyncmediatask.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := asyncmediatask.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := asyncmediatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := asyncmediatask.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.size_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorReason(); ok {
		if err := asyncmediatask.ErrorReasonValidator(v); err != nil {
			return &ValidationError{Name: "error_reason", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.error_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := asyncmediatask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := asyncmediatask.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := asyncmediatask.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InboundEndpoint(); ok {
		if err := asyncmediatask.InboundEndpointValidator(v); err != nil {
			return &ValidationError{Name: "inbound_endpoint", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.inbound_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := asyncmediatask.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_endpoint": %w`, err)}
		}
	}
	return nil
}

func (_u *AsyncMediaTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asyncmediatask.Table, asyncmediatask.Columns, sqlgraph.NewFieldSpec(asyncmediatask.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asyncmediatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InternalRequestID(); ok {
		_spec.SetField(asyncmediatask.FieldInternalRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.StatusURL(); ok {
		_spec.SetField(asyncmediatask.FieldStatusURL, field.TypeString, value)
	}
	if _u.mutation.StatusURLCleared() {
		_spec.ClearField(asyncmediatask.FieldStatusURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseURL(); ok {
		_spec.SetField(asyncmediatask.FieldResponseURL, field.TypeString, value)
	}
	if _u.mutation.ResponseURLCleared() {
		_spec.ClearField(asyncmediatask.FieldResponseURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(asyncmediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(asyncmediatask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(asyncmediatask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(asyncmediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(asyncmediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(asyncmediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(asyncmediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(asyncmediatask.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrganizationID(); ok {
		_spec.AddField(asyncmediatask.FieldOrganizationID, field.TypeInt64, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(asyncmediatask.FieldOrganizationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PayerUserID(); ok {
		_spec.SetField(asyncmediatask.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayerUserID(); ok {
		_spec.AddField(asyncmediatask.FieldPayerUserID, field.TypeInt64, value)
	}
	if _u.mutation.PayerUserIDCleared() {
		_spec.ClearField(asyncmediatask.FieldPayerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BalanceSource(); ok {
		_spec.SetField(asyncmediatask.FieldBalanceSource, field.TypeString, value)
	}
	if _u.mutation.BalanceSourceCleared() {
		_spec.ClearField(asyncmediatask.FieldBalanceSource, field.TypeString)
	}
	if value, ok := _u.mutation.AuthzGeneration(); ok {
		_spec.SetField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthzGeneration(); ok {
		_spec.AddField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64, value)
	}
	if _u.mutation.AuthzGenerationCleared() {
		_spec.ClearField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(asyncmediatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(asyncmediatask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(asyncmediatask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(asyncmediatask.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(asyncmediatask.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(asyncmediatask.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Facade(); ok {
		_spec.SetField(asyncmediatask.FieldFacade, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(asyncmediatask.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(asyncmediatask.FieldImageSize, field.TypeString, value)
	}
	if _u.mutation.ImageSizeCleared() {
		_spec.ClearField(asyncmediatask.FieldImageSize, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(asyncmediatask.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(asyncmediatask.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.NumImages(); ok {
		_spec.SetField(asyncmediatask.FieldNumImages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumImages(); ok {
		_spec.AddField(asyncmediatask.FieldNumImages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestParameters(); ok {
		_spec.SetField(asyncmediatask.FieldRequestParameters, field.TypeJSON, value)
	}
	if _u.mutation.RequestParametersCleared() {
		_spec.ClearField(asyncmediatask.FieldRequestParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(asyncmediatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeldCost(); ok {
		_spec.SetField(asyncmediatask.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeldCost(); ok {
		_spec.AddField(asyncmediatask.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FinalCost(); ok {
		_spec.SetField(asyncmediatask.FieldFinalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFinalCost(); ok {
		_spec.AddField(asyncmediatask.FieldFinalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(asyncmediatask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(asyncmediatask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(asyncmediatask.FieldSizeTier, field.TypeString, value)
	}
	if _u.mutation.SizeTierCleared() {
		_spec.ClearField(asyncmediatask.FieldSizeTier, field.TypeString)
	}
	if value, ok := _u.mutation.ImageUrls(); ok {
		_spec.SetField(asyncmediatask.FieldImageUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImageUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asyncmediatask.FieldImageUrls, value)
		})
	}
	if _u.mutation.ImageUrlsCleared() {
		_spec.ClearField(asyncmediatask.FieldImageUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.CosUrls(); ok {
		_spec.SetField(asyncmediatask.FieldCosUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCosUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asyncmediatask.FieldCosUrls, value)
		})
	}
	if _u.mutation.CosUrlsCleared() {
		_spec.ClearField(asyncmediatask.FieldCosUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(asyncmediatask.FieldErrorReason, field.TypeString, value)
	}
	if _u.mutation.ErrorReasonCleared() {
		_spec.ClearField(asyncmediatask.FieldErrorReason, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(asyncmediatask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(asyncmediatask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailDeadlineAt(); ok {
		_spec.SetField(asyncmediatask.FieldFailDeadlineAt, field.TypeTime, value)
	}
	if _u.mutation.FailDeadlineAtCleared() {
		_spec.ClearField(asyncmediatask.FieldFailDeadlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(asyncmediatask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(asyncmediatask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(asyncmediatask.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(asyncmediatask.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(asyncmediatask.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(asyncmediatask.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.InboundEndpoint(); ok {
		_spec.SetField(asyncmediatask.FieldInboundEndpoint, field.TypeString, value)
	}
	if _u.mutation.InboundEndpointCleared() {
		_spec.ClearField(asyncmediatask.FieldInboundEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if _u.mutation.UpstreamEndpointCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamEndpoint, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asyncmediatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AsyncMediaTaskUpdateOne is the builder for updating a single AsyncMediaTask entity.
type AsyncMediaTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AsyncMediaTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AsyncMediaTaskUpdateOne) SetUpdatedAt(v time.Time) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetInternalRequestID sets the "internal_request_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetInternalRequestID(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetInternalRequestID(v)
	return _u
}

// SetNillableInternalRequestID sets the "internal_request_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableInternalRequestID(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetInternalRequestID(*v)
	}
	return _u
}

// SetUpstreamRequestID sets the "upstream_request_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetUpstreamRequestID(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetUpstreamRequestID(v)
	return _u
}

// SetNillableUpstreamRequestID sets the "upstream_request_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableUpstreamRequestID(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamRequestID(*v)
	}
	return _u
}

// ClearUpstreamRequestID clears the value of the "upstream_request_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearUpstreamRequestID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearUpstreamRequestID()
	return _u
}

// SetStatusURL sets the "status_url" field.
func (_u *AsyncMediaTaskUpdateOne) SetStatusURL(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetStatusURL(v)
	return _u
}

// SetNillableStatusURL sets the "status_url" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableStatusURL(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetStatusURL(*v)
	}
	return _u
}

// ClearStatusURL clears the value of the "status_url" field.
func (_u *AsyncMediaTaskUpdateOne) ClearStatusURL() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearStatusURL()
	return _u
}

// SetResponseURL sets the "response_url" field.
func (_u *AsyncMediaTaskUpdateOne) SetResponseURL(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetResponseURL(v)
	return _u
}

// SetNillableResponseURL sets the "response_url" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableResponseURL(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetResponseURL(*v)
	}
	return _u
}

// ClearResponseURL clears the value of the "response_url" field.
func (_u *AsyncMediaTaskUpdateOne) ClearResponseURL() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearResponseURL()
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetAccountID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableAccountID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddAccountID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// ClearAccountID clears the value of the "account_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearAccountID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearAccountID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetAPIKeyID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableAPIKeyID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddAPIKeyID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetUserID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableUserID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddUserID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetOrganizationID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetOrganizationID()
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableOrganizationID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// AddOrganizationID adds value to the "organization_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddOrganizationID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddOrganizationID(v)
	return _u
}

// ClearOrganizationID clears the value of the "organization_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearOrganizationID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearOrganizationID()
	return _u
}

// SetPayerUserID sets the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetPayerUserID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetPayerUserID()
	_u.mutation.SetPayerUserID(v)
	return _u
}

// SetNillablePayerUserID sets the "payer_user_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillablePayerUserID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetPayerUserID(*v)
	}
	return _u
}

// AddPayerUserID adds value to the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddPayerUserID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddPayerUserID(v)
	return _u
}

// ClearPayerUserID clears the value of the "payer_user_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearPayerUserID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearPayerUserID()
	return _u
}

// SetBalanceSource sets the "balance_source" field.
func (_u *AsyncMediaTaskUpdateOne) SetBalanceSource(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetBalanceSource(v)
	return _u
}

// SetNillableBalanceSource sets the "balance_source" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableBalanceSource(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetBalanceSource(*v)
	}
	return _u
}

// ClearBalanceSource clears the value of the "balance_source" field.
func (_u *AsyncMediaTaskUpdateOne) ClearBalanceSource() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearBalanceSource()
	return _u
}

// SetAuthzGeneration sets the "authz_generation" field.
func (_u *AsyncMediaTaskUpdateOne) SetAuthzGeneration(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetAuthzGeneration()
	_u.mutation.SetAuthzGeneration(v)
	return _u
}

// SetNillableAuthzGeneration sets the "authz_generation" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableAuthzGeneration(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetAuthzGeneration(*v)
	}
	return _u
}

// AddAuthzGeneration adds value to the "authz_generation" field.
func (_u *AsyncMediaTaskUpdateOne) AddAuthzGeneration(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddAuthzGeneration(v)
	return _u
}

// ClearAuthzGeneration clears the value of the "authz_generation" field.
func (_u *AsyncMediaTaskUpdateOne) ClearAuthzGeneration() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearAuthzGeneration()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetGroupID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableGroupID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddGroupID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearGroupID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *AsyncMediaTaskUpdateOne) SetChannelID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetChannelID()
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableChannelID(v *int64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// AddChannelID adds value to the "channel_id" field.
func (_u *AsyncMediaTaskUpdateOne) AddChannelID(v int64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddChannelID(v)
	return _u
}

// ClearChannelID clears the value of the "channel_id" field.
func (_u *AsyncMediaTaskUpdateOne) ClearChannelID() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearChannelID()
	return _u
}

// SetFacade sets the "facade" field.
func (_u *AsyncMediaTaskUpdateOne) SetFacade(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetFacade(v)
	return _u
}

// SetNillableFacade sets the "facade" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableFacade(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetFacade(*v)
	}
	return _u
}

// SetRequestedModel sets the "requested_model" field.
func (_u *AsyncMediaTaskUpdateOne) SetRequestedModel(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetRequestedModel(v)
	return _u
}

// SetNillableRequestedModel sets the "requested_model" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableRequestedModel(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetRequestedModel(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *AsyncMediaTaskUpdateOne) SetUpstreamModel(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableUpstreamModel(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (_u *AsyncMediaTaskUpdateOne) ClearUpstreamModel() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearUpstreamModel()
	return _u
}

// SetImageSize sets the "image_size" field.
func (_u *AsyncMediaTaskUpdateOne) SetImageSize(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetImageSize(v)
	return _u
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableImageSize(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetImageSize(*v)
	}
	return _u
}

// ClearImageSize clears the value of the "image_size" field.
func (_u *AsyncMediaTaskUpdateOne) ClearImageSize() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearImageSize()
	return _u
}

// SetQuality sets the "quality" field.
func (_u *AsyncMediaTaskUpdateOne) SetQuality(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetQuality(v)
	return _u
}

// SetNillableQuality sets the "quality" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableQuality(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetQuality(*v)
	}
	return _u
}

// ClearQuality clears the value of the "quality" field.
func (_u *AsyncMediaTaskUpdateOne) ClearQuality() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearQuality()
	return _u
}

// SetNumImages sets the "num_images" field.
func (_u *AsyncMediaTaskUpdateOne) SetNumImages(v int) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetNumImages()
	_u.mutation.SetNumImages(v)
	return _u
}

// SetNillableNumImages sets the "num_images" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableNumImages(v *int) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetNumImages(*v)
	}
	return _u
}

// AddNumImages adds value to the "num_images" field.
func (_u *AsyncMediaTaskUpdateOne) AddNumImages(v int) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddNumImages(v)
	return _u
}

// SetRequestParameters sets the "request_parameters" field.
func (_u *AsyncMediaTaskUpdateOne) SetRequestParameters(v map[string]interface{}) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetRequestParameters(v)
	return _u
}

// ClearRequestParameters clears the value of the "request_parameters" field.
func (_u *AsyncMediaTaskUpdateOne) ClearRequestParameters() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearRequestParameters()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AsyncMediaTaskUpdateOne) SetStatus(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableStatus(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHeldCost sets the "held_cost" field.
func (_u *AsyncMediaTaskUpdateOne) SetHeldCost(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetHeldCost()
	_u.mutation.SetHeldCost(v)
	return _u
}

// SetNillableHeldCost sets the "held_cost" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableHeldCost(v *float64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetHeldCost(*v)
	}
	return _u
}

// AddHeldCost adds value to the "held_cost" field.
func (_u *AsyncMediaTaskUpdateOne) AddHeldCost(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddHeldCost(v)
	return _u
}

// SetFinalCost sets the "final_cost" field.
func (_u *AsyncMediaTaskUpdateOne) SetFinalCost(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetFinalCost()
	_u.mutation.SetFinalCost(v)
	return _u
}

// SetNillableFinalCost sets the "final_cost" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableFinalCost(v *float64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetFinalCost(*v)
	}
	return _u
}

// AddFinalCost adds value to the "final_cost" field.
func (_u *AsyncMediaTaskUpdateOne) AddFinalCost(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddFinalCost(v)
	return _u
}

// SetRateMultiplier sets the "rate_multiplier" field.
func (_u *AsyncMediaTaskUpdateOne) SetRateMultiplier(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.ResetRateMultiplier()
	_u.mutation.SetRateMultiplier(v)
	return _u
}

// SetNillableRateMultiplier sets the "rate_multiplier" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableRateMultiplier(v *float64) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetRateMultiplier(*v)
	}
	return _u
}

// AddRateMultiplier adds value to the "rate_multiplier" field.
func (_u *AsyncMediaTaskUpdateOne) AddRateMultiplier(v float64) *AsyncMediaTaskUpdateOne {
	_u.mutation.AddRateMultiplier(v)
	return _u
}

// SetSizeTier sets the "size_tier" field.
func (_u *AsyncMediaTaskUpdateOne) SetSizeTier(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetSizeTier(v)
	return _u
}

// SetNillableSizeTier sets the "size_tier" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableSizeTier(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetSizeTier(*v)
	}
	return _u
}

// ClearSizeTier clears the value of the "size_tier" field.
func (_u *AsyncMediaTaskUpdateOne) ClearSizeTier() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearSizeTier()
	return _u
}

// SetImageUrls sets the "image_urls" field.
func (_u *AsyncMediaTaskUpdateOne) SetImageUrls(v []string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetImageUrls(v)
	return _u
}

// AppendImageUrls appends value to the "image_urls" field.
func (_u *AsyncMediaTaskUpdateOne) AppendImageUrls(v []string) *AsyncMediaTaskUpdateOne {
	_u.mutation.AppendImageUrls(v)
	return _u
}

// ClearImageUrls clears the value of the "image_urls" field.
func (_u *AsyncMediaTaskUpdateOne) ClearImageUrls() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearImageUrls()
	return _u
}

// SetCosUrls sets the "cos_urls" field.
func (_u *AsyncMediaTaskUpdateOne) SetCosUrls(v []string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetCosUrls(v)
	return _u
}

// AppendCosUrls appends value to the "cos_urls" field.
func (_u *AsyncMediaTaskUpdateOne) AppendCosUrls(v []string) *AsyncMediaTaskUpdateOne {
	_u.mutation.AppendCosUrls(v)
	return _u
}

// ClearCosUrls clears the value of the "cos_urls" field.
func (_u *AsyncMediaTaskUpdateOne) ClearCosUrls() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearCosUrls()
	return _u
}

// SetErrorReason sets the "error_reason" field.
func (_u *AsyncMediaTaskUpdateOne) SetErrorReason(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetErrorReason(v)
	return _u
}

// SetNillableErrorReason sets the "error_reason" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableErrorReason(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetErrorReason(*v)
	}
	return _u
}

// ClearErrorReason clears the value of the "error_reason" field.
func (_u *AsyncMediaTaskUpdateOne) ClearErrorReason() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearErrorReason()
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *AsyncMediaTaskUpdateOne) SetErrorCode(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableErrorCode(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *AsyncMediaTaskUpdateOne) ClearErrorCode() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetFailDeadlineAt sets the "fail_deadline_at" field.
func (_u *AsyncMediaTaskUpdateOne) SetFailDeadlineAt(v time.Time) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetFailDeadlineAt(v)
	return _u
}

// SetNillableFailDeadlineAt sets the "fail_deadline_at" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableFailDeadlineAt(v *time.Time) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetFailDeadlineAt(*v)
	}
	return _u
}

// ClearFailDeadlineAt clears the value of the "fail_deadline_at" field.
func (_u *AsyncMediaTaskUpdateOne) ClearFailDeadlineAt() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearFailDeadlineAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *AsyncMediaTaskUpdateOne) SetFinishedAt(v time.Time) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableFinishedAt(v *time.Time) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *AsyncMediaTaskUpdateOne) ClearFinishedAt() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetClientIP sets the "client_ip" field.
func (_u *AsyncMediaTaskUpdateOne) SetClientIP(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetClientIP(v)
	return _u
}

// SetNillableClientIP sets the "client_ip" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableClientIP(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetClientIP(*v)
	}
	return _u
}

// ClearClientIP clears the value of the "client_ip" field.
func (_u *AsyncMediaTaskUpdateOne) ClearClientIP() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearClientIP()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *AsyncMediaTaskUpdateOne) SetUserAgent(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableUserAgent(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *AsyncMediaTaskUpdateOne) ClearUserAgent() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetInboundEndpoint sets the "inbound_endpoint" field.
func (_u *AsyncMediaTaskUpdateOne) SetInboundEndpoint(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetInboundEndpoint(v)
	return _u
}

// SetNillableInboundEndpoint sets the "inbound_endpoint" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableInboundEndpoint(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetInboundEndpoint(*v)
	}
	return _u
}

// ClearInboundEndpoint clears the value of the "inbound_endpoint" field.
func (_u *AsyncMediaTaskUpdateOne) ClearInboundEndpoint() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearInboundEndpoint()
	return _u
}

// SetUpstreamEndpoint sets the "upstream_endpoint" field.
func (_u *AsyncMediaTaskUpdateOne) SetUpstreamEndpoint(v string) *AsyncMediaTaskUpdateOne {
	_u.mutation.SetUpstreamEndpoint(v)
	return _u
}

// SetNillableUpstreamEndpoint sets the "upstream_endpoint" field if the given value is not nil.
func (_u *AsyncMediaTaskUpdateOne) SetNillableUpstreamEndpoint(v *string) *AsyncMediaTaskUpdateOne {
	if v != nil {
		_u.SetUpstreamEndpoint(*v)
	}
	return _u
}

// ClearUpstreamEndpoint clears the value of the "upstream_endpoint" field.
func (_u *AsyncMediaTaskUpdateOne) ClearUpstreamEndpoint() *AsyncMediaTaskUpdateOne {
	_u.mutation.ClearUpstreamEndpoint()
	return _u
}

// Mutation returns the AsyncMediaTaskMutation object of the builder.
func (_u *AsyncMediaTaskUpdateOne) Mutation() *AsyncMediaTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the AsyncMediaTaskUpdate builder.
func (_u *AsyncMediaTaskUpdateOne) Where(ps ...predicate.AsyncMediaTask) *AsyncMediaTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AsyncMediaTaskUpdateOne) Select(field string, fields ...string) *AsyncMediaTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AsyncMediaTask entity.
func (_u *AsyncMediaTaskUpdateOne) Save(ctx context.Context) (*AsyncMediaTask, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AsyncMediaTaskUpdateOne) SaveX(ctx context.Context) *AsyncMediaTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AsyncMediaTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AsyncMediaTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AsyncMediaTaskUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := asyncmediatask.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AsyncMediaTaskUpdateOne) check() error {
	if v, ok := _u.mutation.InternalRequestID(); ok {
		if err := asyncmediatask.InternalRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "internal_request_id", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.internal_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamRequestID(); ok {
		if err := asyncmediatask.UpstreamRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_request_id", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StatusURL(); ok {
		if err := asyncmediatask.StatusURLValidator(v); err != nil {
			return &ValidationError{Name: "status_url", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.status_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ResponseURL(); ok {
		if err := asyncmediatask.ResponseURLValidator(v); err != nil {
			return &ValidationError{Name: "response_url", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.response_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BalanceSource(); ok {
		if err := asyncmediatask.BalanceSourceValidator(v); err != nil {
			return &ValidationError{Name: "balance_source", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.balance_source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Facade(); ok {
		if err := asyncmediatask.FacadeValidator(v); err != nil {
			return &ValidationError{Name: "facade", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.facade": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestedModel(); ok {
		if err := asyncmediatask.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.requested_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := asyncmediatask.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ImageSize(); ok {
		if err := asyncmediatask.ImageSizeValidator(v); err != nil {
			return &ValidationError{Name: "image_size", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.image_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quality(); ok {
		if err := asyncmediatask.QualityValidator(v); err != nil {
			return &ValidationError{Name: "quality", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.quality": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := asyncmediatask.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SizeTier(); ok {
		if err := asyncmediatask.SizeTierValidator(v); err != nil {
			return &ValidationError{Name: "size_tier", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.size_tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorReason(); ok {
		if err := asyncmediatask.ErrorReasonValidator(v); err != nil {
			return &ValidationError{Name: "error_reason", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.error_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := asyncmediatask.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientIP(); ok {
		if err := asyncmediatask.ClientIPValidator(v); err != nil {
			return &ValidationError{Name: "client_ip", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.client_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAgent(); ok {
		if err := asyncmediatask.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.user_agent": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InboundEndpoint(); ok {
		if err := asyncmediatask.InboundEndpointValidator(v); err != nil {
			return &ValidationError{Name: "inbound_endpoint", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.inbound_endpoint": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamEndpoint(); ok {
		if err := asyncmediatask.UpstreamEndpointValidator(v); err != nil {
			return &ValidationError{Name: "upstream_endpoint", err: fmt.Errorf(`ent: validator failed for field "AsyncMediaTask.upstream_endpoint": %w`, err)}
		}
	}
	return nil
}

func (_u *AsyncMediaTaskUpdateOne) sqlSave(ctx context.Context) (_node *AsyncMediaTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(asyncmediatask.Table, asyncmediatask.Columns, sqlgraph.NewFieldSpec(asyncmediatask.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AsyncMediaTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, asyncmediatask.FieldID)
		for _, f := range fields {
			if !asyncmediatask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != asyncmediatask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(asyncmediatask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.InternalRequestID(); ok {
		_spec.SetField(asyncmediatask.FieldInternalRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamRequestID(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamRequestID, field.TypeString, value)
	}
	if _u.mutation.UpstreamRequestIDCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.StatusURL(); ok {
		_spec.SetField(asyncmediatask.FieldStatusURL, field.TypeString, value)
	}
	if _u.mutation.StatusURLCleared() {
		_spec.ClearField(asyncmediatask.FieldStatusURL, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseURL(); ok {
		_spec.SetField(asyncmediatask.FieldResponseURL, field.TypeString, value)
	}
	if _u.mutation.ResponseURLCleared() {
		_spec.ClearField(asyncmediatask.FieldResponseURL, field.TypeString)
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(asyncmediatask.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(asyncmediatask.FieldAccountID, field.TypeInt64, value)
	}
	if _u.mutation.AccountIDCleared() {
		_spec.ClearField(asyncmediatask.FieldAccountID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(asyncmediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(asyncmediatask.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(asyncmediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(asyncmediatask.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(asyncmediatask.FieldOrganizationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrganizationID(); ok {
		_spec.AddField(asyncmediatask.FieldOrganizationID, field.TypeInt64, value)
	}
	if _u.mutation.OrganizationIDCleared() {
		_spec.ClearField(asyncmediatask.FieldOrganizationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.PayerUserID(); ok {
		_spec.SetField(asyncmediatask.FieldPayerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPayerUserID(); ok {
		_spec.AddField(asyncmediatask.FieldPayerUserID, field.TypeInt64, value)
	}
	if _u.mutation.PayerUserIDCleared() {
		_spec.ClearField(asyncmediatask.FieldPayerUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.BalanceSource(); ok {
		_spec.SetField(asyncmediatask.FieldBalanceSource, field.TypeString, value)
	}
	if _u.mutation.BalanceSourceCleared() {
		_spec.ClearField(asyncmediatask.FieldBalanceSource, field.TypeString)
	}
	if value, ok := _u.mutation.AuthzGeneration(); ok {
		_spec.SetField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAuthzGeneration(); ok {
		_spec.AddField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64, value)
	}
	if _u.mutation.AuthzGenerationCleared() {
		_spec.ClearField(asyncmediatask.FieldAuthzGeneration, field.TypeInt64)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(asyncmediatask.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(asyncmediatask.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(asyncmediatask.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(asyncmediatask.FieldChannelID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChannelID(); ok {
		_spec.AddField(asyncmediatask.FieldChannelID, field.TypeInt64, value)
	}
	if _u.mutation.ChannelIDCleared() {
		_spec.ClearField(asyncmediatask.FieldChannelID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Facade(); ok {
		_spec.SetField(asyncmediatask.FieldFacade, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestedModel(); ok {
		_spec.SetField(asyncmediatask.FieldRequestedModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamModel, field.TypeString, value)
	}
	if _u.mutation.UpstreamModelCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamModel, field.TypeString)
	}
	if value, ok := _u.mutation.ImageSize(); ok {
		_spec.SetField(asyncmediatask.FieldImageSize, field.TypeString, value)
	}
	if _u.mutation.ImageSizeCleared() {
		_spec.ClearField(asyncmediatask.FieldImageSize, field.TypeString)
	}
	if value, ok := _u.mutation.Quality(); ok {
		_spec.SetField(asyncmediatask.FieldQuality, field.TypeString, value)
	}
	if _u.mutation.QualityCleared() {
		_spec.ClearField(asyncmediatask.FieldQuality, field.TypeString)
	}
	if value, ok := _u.mutation.NumImages(); ok {
		_spec.SetField(asyncmediatask.FieldNumImages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNumImages(); ok {
		_spec.AddField(asyncmediatask.FieldNumImages, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequestParameters(); ok {
		_spec.SetField(asyncmediatask.FieldRequestParameters, field.TypeJSON, value)
	}
	if _u.mutation.RequestParametersCleared() {
		_spec.ClearField(asyncmediatask.FieldRequestParameters, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(asyncmediatask.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.HeldCost(); ok {
		_spec.SetField(asyncmediatask.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHeldCost(); ok {
		_spec.AddField(asyncmediatask.FieldHeldCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FinalCost(); ok {
		_spec.SetField(asyncmediatask.FieldFinalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFinalCost(); ok {
		_spec.AddField(asyncmediatask.FieldFinalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RateMultiplier(); ok {
		_spec.SetField(asyncmediatask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRateMultiplier(); ok {
		_spec.AddField(asyncmediatask.FieldRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SizeTier(); ok {
		_spec.SetField(asyncmediatask.FieldSizeTier, field.TypeString, value)
	}
	if _u.mutation.SizeTierCleared() {
		_spec.ClearField(asyncmediatask.FieldSizeTier, field.TypeString)
	}
	if value, ok := _u.mutation.ImageUrls(); ok {
		_spec.SetField(asyncmediatask.FieldImageUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImageUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asyncmediatask.FieldImageUrls, value)
		})
	}
	if _u.mutation.ImageUrlsCleared() {
		_spec.ClearField(asyncmediatask.FieldImageUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.CosUrls(); ok {
		_spec.SetField(asyncmediatask.FieldCosUrls, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedCosUrls(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, asyncmediatask.FieldCosUrls, value)
		})
	}
	if _u.mutation.CosUrlsCleared() {
		_spec.ClearField(asyncmediatask.FieldCosUrls, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorReason(); ok {
		_spec.SetField(asyncmediatask.FieldErrorReason, field.TypeString, value)
	}
	if _u.mutation.ErrorReasonCleared() {
		_spec.ClearField(asyncmediatask.FieldErrorReason, field.TypeString)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(asyncmediatask.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(asyncmediatask.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.FailDeadlineAt(); ok {
		_spec.SetField(asyncmediatask.FieldFailDeadlineAt, field.TypeTime, value)
	}
	if _u.mutation.FailDeadlineAtCleared() {
		_spec.ClearField(asyncmediatask.FieldFailDeadlineAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(asyncmediatask.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(asyncmediatask.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientIP(); ok {
		_spec.SetField(asyncmediatask.FieldClientIP, field.TypeString, value)
	}
	if _u.mutation.ClientIPCleared() {
		_spec.ClearField(asyncmediatask.FieldClientIP, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(asyncmediatask.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(asyncmediatask.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.InboundEndpoint(); ok {
		_spec.SetField(asyncmediatask.FieldInboundEndpoint, field.TypeString, value)
	}
	if _u.mutation.InboundEndpointCleared() {
		_spec.ClearField(asyncmediatask.FieldInboundEndpoint, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamEndpoint(); ok {
		_spec.SetField(asyncmediatask.FieldUpstreamEndpoint, field.TypeString, value)
	}
	if _u.mutation.UpstreamEndpointCleared() {
		_spec.ClearField(asyncmediatask.FieldUpstreamEndpoint, field.TypeString)
	}
	_node = &AsyncMediaTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{asyncmediatask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
