// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/asyncmediatask"
)

// AsyncMediaTask is the model entity for the AsyncMediaTask schema.
type AsyncMediaTask struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 网关内部请求 ID（对外暴露给客户端轮询）
	InternalRequestID string `json:"internal_request_id,omitempty"`
	// 上游 fal request_id（提交成功后回填）
	UpstreamRequestID *string `json:"upstream_request_id,omitempty"`
	// 上游 status_url（以提交响应为准，避免手拼路径）
	StatusURL *string `json:"status_url,omitempty"`
	// 上游 response_url（取结果地址）
	ResponseURL *string `json:"response_url,omitempty"`
	// 选中的上游账号 ID
	AccountID *int64 `json:"account_id,omitempty"`
	// 发起请求的 API Key ID
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// 所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// OrganizationID holds the value of the "organization_id" field.
	OrganizationID *int64 `json:"organization_id,omitempty"`
	// PayerUserID holds the value of the "payer_user_id" field.
	PayerUserID *int64 `json:"payer_user_id,omitempty"`
	// BalanceSource holds the value of the "balance_source" field.
	BalanceSource *string `json:"balance_source,omitempty"`
	// AuthzGeneration holds the value of the "authz_generation" field.
	AuthzGeneration *int64 `json:"authz_generation,omitempty"`
	// 所属分组 ID
	GroupID *int64 `json:"group_id,omitempty"`
	// 命中的渠道 ID
	ChannelID *int64 `json:"channel_id,omitempty"`
	// 对外门面协议：openai（伪同步）/ fal（原生异步）
	Facade string `json:"facade,omitempty"`
	// 客户端请求的模型名
	RequestedModel string `json:"requested_model,omitempty"`
	// 映射后的上游模型/slug
	UpstreamModel *string `json:"upstream_model,omitempty"`
	// 请求的图片尺寸（OpenAI 形式或 fal 枚举）
	ImageSize *string `json:"image_size,omitempty"`
	// 图片质量（auto/low/medium/high 等）
	Quality *string `json:"quality,omitempty"`
	// 请求生成的图片数量
	NumImages int `json:"num_images,omitempty"`
	// 脱敏后的客户端请求参数
	RequestParameters map[string]interface{} `json:"request_parameters,omitempty"`
	// 任务状态：pending/running/succeeded/failed/refunded/expired
	Status string `json:"status,omitempty"`
	// 预扣费金额
	HeldCost float64 `json:"held_cost,omitempty"`
	// 结算费用（成功后写入；退费置 0）
	FinalCost float64 `json:"final_cost,omitempty"`
	// 计费倍率快照
	RateMultiplier float64 `json:"rate_multiplier,omitempty"`
	// 计费用尺寸档位快照（1K/2K/4K 等）
	SizeTier *string `json:"size_tier,omitempty"`
	// 成功出图的 fal 原始 url 列表
	ImageUrls []string `json:"image_urls,omitempty"`
	// 转存 COS 后的 url 列表（转存失败则留空）
	CosUrls []string `json:"cos_urls,omitempty"`
	// 失败/退费原因
	ErrorReason *string `json:"error_reason,omitempty"`
	// 对外项目错误码
	ErrorCode *string `json:"error_code,omitempty"`
	// 失败兜底截止时间（到达仍未完成则判定超期退费）
	FailDeadlineAt *time.Time `json:"fail_deadline_at,omitempty"`
	// 任务终结时间
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// 客户端 IP
	ClientIP *string `json:"client_ip,omitempty"`
	// 客户端 User-Agent
	UserAgent *string `json:"user_agent,omitempty"`
	// 对外门面端点（客户端可见路径）
	InboundEndpoint *string `json:"inbound_endpoint,omitempty"`
	// 上游 fal 端点（提交所用 slug 路径）
	UpstreamEndpoint *string `json:"upstream_endpoint,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AsyncMediaTask) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case asyncmediatask.FieldRequestParameters, asyncmediatask.FieldImageUrls, asyncmediatask.FieldCosUrls:
			values[i] = new([]byte)
		case asyncmediatask.FieldHeldCost, asyncmediatask.FieldFinalCost, asyncmediatask.FieldRateMultiplier:
			values[i] = new(sql.NullFloat64)
		case asyncmediatask.FieldID, asyncmediatask.FieldAccountID, asyncmediatask.FieldAPIKeyID, asyncmediatask.FieldUserID, asyncmediatask.FieldOrganizationID, asyncmediatask.FieldPayerUserID, asyncmediatask.FieldAuthzGeneration, asyncmediatask.FieldGroupID, asyncmediatask.FieldChannelID, asyncmediatask.FieldNumImages:
			values[i] = new(sql.NullInt64)
		case asyncmediatask.FieldInternalRequestID, asyncmediatask.FieldUpstreamRequestID, asyncmediatask.FieldStatusURL, asyncmediatask.FieldResponseURL, asyncmediatask.FieldBalanceSource, asyncmediatask.FieldFacade, asyncmediatask.FieldRequestedModel, asyncmediatask.FieldUpstreamModel, asyncmediatask.FieldImageSize, asyncmediatask.FieldQuality, asyncmediatask.FieldStatus, asyncmediatask.FieldSizeTier, asyncmediatask.FieldErrorReason, asyncmediatask.FieldErrorCode, asyncmediatask.FieldClientIP, asyncmediatask.FieldUserAgent, asyncmediatask.FieldInboundEndpoint, asyncmediatask.FieldUpstreamEndpoint:
			values[i] = new(sql.NullString)
		case asyncmediatask.FieldCreatedAt, asyncmediatask.FieldUpdatedAt, asyncmediatask.FieldFailDeadlineAt, asyncmediatask.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AsyncMediaTask fields.
func (_m *AsyncMediaTask) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case asyncmediatask.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case asyncmediatask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case asyncmediatask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case asyncmediatask.FieldInternalRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_request_id", values[i])
			} else if value.Valid {
				_m.InternalRequestID = value.String
			}
		case asyncmediatask.FieldUpstreamRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_request_id", values[i])
			} else if value.Valid {
				_m.UpstreamRequestID = new(string)
				*_m.UpstreamRequestID = value.String
			}
		case asyncmediatask.FieldStatusURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status_url", values[i])
			} else if value.Valid {
				_m.StatusURL = new(string)
				*_m.StatusURL = value.String
			}
		case asyncmediatask.FieldResponseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_url", values[i])
			} else if value.Valid {
				_m.ResponseURL = new(string)
				*_m.ResponseURL = value.String
			}
		case asyncmediatask.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case asyncmediatask.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case asyncmediatask.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case asyncmediatask.FieldOrganizationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field organization_id", values[i])
			} else if value.Valid {
				_m.OrganizationID = new(int64)
				*_m.OrganizationID = value.Int64
			}
		case asyncmediatask.FieldPayerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payer_user_id", values[i])
			} else if value.Valid {
				_m.PayerUserID = new(int64)
				*_m.PayerUserID = value.Int64
			}
		case asyncmediatask.FieldBalanceSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field balance_source", values[i])
			} else if value.Valid {
				_m.BalanceSource = new(string)
				*_m.BalanceSource = value.String
			}
		case asyncmediatask.FieldAuthzGeneration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field authz_generation", values[i])
			} else if value.Valid {
				_m.AuthzGeneration = new(int64)
				*_m.AuthzGeneration = value.Int64
			}
		case asyncmediatask.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case asyncmediatask.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = new(int64)
				*_m.ChannelID = value.Int64
			}
		case asyncmediatask.FieldFacade:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field facade", values[i])
			} else if value.Valid {
				_m.Facade = value.String
			}
		case asyncmediatask.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case asyncmediatask.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = new(string)
				*_m.UpstreamModel = value.String
			}
		case asyncmediatask.FieldImageSize:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_size", values[i])
			} else if value.Valid {
				_m.ImageSize = new(string)
				*_m.ImageSize = value.String
			}
		case asyncmediatask.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = new(string)
				*_m.Quality = value.String
			}
		case asyncmediatask.FieldNumImages:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field num_images", values[i])
			} else if value.Valid {
				_m.NumImages = int(value.Int64)
			}
		case asyncmediatask.FieldRequestParameters:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field request_parameters", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RequestParameters); err != nil {
					return fmt.Errorf("unmarshal field request_parameters: %w", err)
				}
			}
		case asyncmediatask.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case asyncmediatask.FieldHeldCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field held_cost", values[i])
			} else if value.Valid {
				_m.HeldCost = value.Float64
			}
		case asyncmediatask.FieldFinalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field final_cost", values[i])
			} else if value.Valid {
				_m.FinalCost = value.Float64
			}
		case asyncmediatask.FieldRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_multiplier", values[i])
			} else if value.Valid {
				_m.RateMultiplier = value.Float64
			}
		case asyncmediatask.FieldSizeTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field size_tier", values[i])
			} else if value.Valid {
				_m.SizeTier = new(string)
				*_m.SizeTier = value.String
			}
		case asyncmediatask.FieldImageUrls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field image_urls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ImageUrls); err != nil {
					return fmt.Errorf("unmarshal field image_urls: %w", err)
				}
			}
		case asyncmediatask.FieldCosUrls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field cos_urls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CosUrls); err != nil {
					return fmt.Errorf("unmarshal field cos_urls: %w", err)
				}
			}
		case asyncmediatask.FieldErrorReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_reason", values[i])
			} else if value.Valid {
				_m.ErrorReason = new(string)
				*_m.ErrorReason = value.String
			}
		case asyncmediatask.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = new(string)
				*_m.ErrorCode = value.String
			}
		case asyncmediatask.FieldFailDeadlineAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field fail_deadline_at", values[i])
			} else if value.Valid {
				_m.FailDeadlineAt = new(time.Time)
				*_m.FailDeadlineAt = value.Time
			}
		case asyncmediatask.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case asyncmediatask.FieldClientIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_ip", values[i])
			} else if value.Valid {
				_m.ClientIP = new(string)
				*_m.ClientIP = value.String
			}
		case asyncmediatask.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				_m.UserAgent = new(string)
				*_m.UserAgent = value.String
			}
		case asyncmediatask.FieldInboundEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inbound_endpoint", values[i])
			} else if value.Valid {
				_m.InboundEndpoint = new(string)
				*_m.InboundEndpoint = value.String
			}
		case asyncmediatask.FieldUpstreamEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_endpoint", values[i])
			} else if value.Valid {
				_m.UpstreamEndpoint = new(string)
				*_m.UpstreamEndpoint = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AsyncMediaTask.
// This includes values selected through modifiers, order, etc.
func (_m *AsyncMediaTask) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AsyncMediaTask.
// Note that you need to call AsyncMediaTask.Unwrap() before calling this method if this AsyncMediaTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AsyncMediaTask) Update() *AsyncMediaTaskUpdateOne {
	return NewAsyncMediaTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AsyncMediaTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AsyncMediaTask) Unwrap() *AsyncMediaTask {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AsyncMediaTask is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AsyncMediaTask) String() string {
	var builder strings.Builder
	builder.WriteString("AsyncMediaTask(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("internal_request_id=")
	builder.WriteString(_m.InternalRequestID)
	builder.WriteString(", ")
	if v := _m.UpstreamRequestID; v != nil {
		builder.WriteString("upstream_request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.StatusURL; v != nil {
		builder.WriteString("status_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponseURL; v != nil {
		builder.WriteString("response_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.OrganizationID; v != nil {
		builder.WriteString("organization_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PayerUserID; v != nil {
		builder.WriteString("payer_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BalanceSource; v != nil {
		builder.WriteString("balance_source=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AuthzGeneration; v != nil {
		builder.WriteString("authz_generation=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ChannelID; v != nil {
		builder.WriteString("channel_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("facade=")
	builder.WriteString(_m.Facade)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	if v := _m.UpstreamModel; v != nil {
		builder.WriteString("upstream_model=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ImageSize; v != nil {
		builder.WriteString("image_size=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Quality; v != nil {
		builder.WriteString("quality=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("num_images=")
	builder.WriteString(fmt.Sprintf("%v", _m.NumImages))
	builder.WriteString(", ")
	builder.WriteString("request_parameters=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestParameters))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("held_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.HeldCost))
	builder.WriteString(", ")
	builder.WriteString("final_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.FinalCost))
	builder.WriteString(", ")
	builder.WriteString("rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateMultiplier))
	builder.WriteString(", ")
	if v := _m.SizeTier; v != nil {
		builder.WriteString("size_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("image_urls=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImageUrls))
	builder.WriteString(", ")
	builder.WriteString("cos_urls=")
	builder.WriteString(fmt.Sprintf("%v", _m.CosUrls))
	builder.WriteString(", ")
	if v := _m.ErrorReason; v != nil {
		builder.WriteString("error_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ErrorCode; v != nil {
		builder.WriteString("error_code=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FailDeadlineAt; v != nil {
		builder.WriteString("fail_deadline_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClientIP; v != nil {
		builder.WriteString("client_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAgent; v != nil {
		builder.WriteString("user_agent=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.InboundEndpoint; v != nil {
		builder.WriteString("inbound_endpoint=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UpstreamEndpoint; v != nil {
		builder.WriteString("upstream_endpoint=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// AsyncMediaTasks is a parsable slice of AsyncMediaTask.
type AsyncMediaTasks []*AsyncMediaTask
