// Code generated by ent, DO NOT EDIT.

package asyncmediatask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the asyncmediatask type in the database.
	Label = "async_media_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldInternalRequestID holds the string denoting the internal_request_id field in the database.
	FieldInternalRequestID = "internal_request_id"
	// FieldUpstreamRequestID holds the string denoting the upstream_request_id field in the database.
	FieldUpstreamRequestID = "upstream_request_id"
	// FieldStatusURL holds the string denoting the status_url field in the database.
	FieldStatusURL = "status_url"
	// FieldResponseURL holds the string denoting the response_url field in the database.
	FieldResponseURL = "response_url"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldPayerUserID holds the string denoting the payer_user_id field in the database.
	FieldPayerUserID = "payer_user_id"
	// FieldBalanceSource holds the string denoting the balance_source field in the database.
	FieldBalanceSource = "balance_source"
	// FieldAuthzGeneration holds the string denoting the authz_generation field in the database.
	FieldAuthzGeneration = "authz_generation"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldFacade holds the string denoting the facade field in the database.
	FieldFacade = "facade"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldImageSize holds the string denoting the image_size field in the database.
	FieldImageSize = "image_size"
	// FieldQuality holds the string denoting the quality field in the database.
	FieldQuality = "quality"
	// FieldNumImages holds the string denoting the num_images field in the database.
	FieldNumImages = "num_images"
	// FieldRequestParameters holds the string denoting the request_parameters field in the database.
	FieldRequestParameters = "request_parameters"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldHeldCost holds the string denoting the held_cost field in the database.
	FieldHeldCost = "held_cost"
	// FieldFinalCost holds the string denoting the final_cost field in the database.
	FieldFinalCost = "final_cost"
	// FieldRateMultiplier holds the string denoting the rate_multiplier field in the database.
	FieldRateMultiplier = "rate_multiplier"
	// FieldSizeTier holds the string denoting the size_tier field in the database.
	FieldSizeTier = "size_tier"
	// FieldImageUrls holds the string denoting the image_urls field in the database.
	FieldImageUrls = "image_urls"
	// FieldCosUrls holds the string denoting the cos_urls field in the database.
	FieldCosUrls = "cos_urls"
	// FieldErrorReason holds the string denoting the error_reason field in the database.
	FieldErrorReason = "error_reason"
	// FieldErrorCode holds the string denoting the error_code field in the database.
	FieldErrorCode = "error_code"
	// FieldFailDeadlineAt holds the string denoting the fail_deadline_at field in the database.
	FieldFailDeadlineAt = "fail_deadline_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldClientIP holds the string denoting the client_ip field in the database.
	FieldClientIP = "client_ip"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldInboundEndpoint holds the string denoting the inbound_endpoint field in the database.
	FieldInboundEndpoint = "inbound_endpoint"
	// FieldUpstreamEndpoint holds the string denoting the upstream_endpoint field in the database.
	FieldUpstreamEndpoint = "upstream_endpoint"
	// Table holds the table name of the asyncmediatask in the database.
	Table = "async_media_tasks"
)

// Columns holds all SQL columns for asyncmediatask fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldInternalRequestID,
	FieldUpstreamRequestID,
	FieldStatusURL,
	FieldResponseURL,
	FieldAccountID,
	FieldAPIKeyID,
	FieldUserID,
	FieldOrganizationID,
	FieldPayerUserID,
	FieldBalanceSource,
	FieldAuthzGeneration,
	FieldGroupID,
	FieldChannelID,
	FieldFacade,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldImageSize,
	FieldQuality,
	FieldNumImages,
	FieldRequestParameters,
	FieldStatus,
	FieldHeldCost,
	FieldFinalCost,
	FieldRateMultiplier,
	FieldSizeTier,
	FieldImageUrls,
	FieldCosUrls,
	FieldErrorReason,
	FieldErrorCode,
	FieldFailDeadlineAt,
	FieldFinishedAt,
	FieldClientIP,
	FieldUserAgent,
	FieldInboundEndpoint,
	FieldUpstreamEndpoint,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// InternalRequestIDValidator is a validator for the "internal_request_id" field. It is called by the builders before save.
	InternalRequestIDValidator func(string) error
	// UpstreamRequestIDValidator is a validator for the "upstream_request_id" field. It is called by the builders before save.
	UpstreamRequestIDValidator func(string) error
	// StatusURLValidator is a validator for the "status_url" field. It is called by the builders before save.
	StatusURLValidator func(string) error
	// ResponseURLValidator is a validator for the "response_url" field. It is called by the builders before save.
	ResponseURLValidator func(string) error
	// BalanceSourceValidator is a validator for the "balance_source" field. It is called by the builders before save.
	BalanceSourceValidator func(string) error
	// DefaultFacade holds the default value on creation for the "facade" field.
	DefaultFacade string
	// FacadeValidator is a validator for the "facade" field. It is called by the builders before save.
	FacadeValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// ImageSizeValidator is a validator for the "image_size" field. It is called by the builders before save.
	ImageSizeValidator func(string) error
	// QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	QualityValidator func(string) error
	// DefaultNumImages holds the default value on creation for the "num_images" field.
	DefaultNumImages int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultHeldCost holds the default value on creation for the "held_cost" field.
	DefaultHeldCost float64
	// DefaultFinalCost holds the default value on creation for the "final_cost" field.
	DefaultFinalCost float64
	// DefaultRateMultiplier holds the default value on creation for the "rate_multiplier" field.
	DefaultRateMultiplier float64
	// SizeTierValidator is a validator for the "size_tier" field. It is called by the builders before save.
	SizeTierValidator func(string) error
	// ErrorReasonValidator is a validator for the "error_reason" field. It is called by the builders before save.
	ErrorReasonValidator func(string) error
	// ErrorCodeValidator is a validator for the "error_code" field. It is called by the builders before save.
	ErrorCodeValidator func(string) error
	// ClientIPValidator is a validator for the "client_ip" field. It is called by the builders before save.
	ClientIPValidator func(string) error
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// InboundEndpointValidator is a validator for the "inbound_endpoint" field. It is called by the builders before save.
	InboundEndpointValidator func(string) error
	// UpstreamEndpointValidator is a validator for the "upstream_endpoint" field. It is called by the builders before save.
	UpstreamEndpointValidator func(string) error
)

// OrderOption defines the ordering options for the AsyncMediaTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInternalRequestID orders the results by the internal_request_id field.
func ByInternalRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalRequestID, opts...).ToFunc()
}

// ByUpstreamRequestID orders the results by the upstream_request_id field.
func ByUpstreamRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamRequestID, opts...).ToFunc()
}

// ByStatusURL orders the results by the status_url field.
func ByStatusURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusURL, opts...).ToFunc()
}

// ByResponseURL orders the results by the response_url field.
func ByResponseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseURL, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByPayerUserID orders the results by the payer_user_id field.
func ByPayerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayerUserID, opts...).ToFunc()
}

// ByBalanceSource orders the results by the balance_source field.
func ByBalanceSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceSource, opts...).ToFunc()
}

// ByAuthzGeneration orders the results by the authz_generation field.
func ByAuthzGeneration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthzGeneration, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByFacade orders the results by the facade field.
func ByFacade(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFacade, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByImageSize orders the results by the image_size field.
func ByImageSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageSize, opts...).ToFunc()
}

// ByQuality orders the results by the quality field.
func ByQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuality, opts...).ToFunc()
}

// ByNumImages orders the results by the num_images field.
func ByNumImages(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumImages, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByHeldCost orders the results by the held_cost field.
func ByHeldCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHeldCost, opts...).ToFunc()
}

// ByFinalCost orders the results by the final_cost field.
func ByFinalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalCost, opts...).ToFunc()
}

// ByRateMultiplier orders the results by the rate_multiplier field.
func ByRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRateMultiplier, opts...).ToFunc()
}

// BySizeTier orders the results by the size_tier field.
func BySizeTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSizeTier, opts...).ToFunc()
}

// ByErrorReason orders the results by the error_reason field.
func ByErrorReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorReason, opts...).ToFunc()
}

// ByErrorCode orders the results by the error_code field.
func ByErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorCode, opts...).ToFunc()
}

// ByFailDeadlineAt orders the results by the fail_deadline_at field.
func ByFailDeadlineAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailDeadlineAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByClientIP orders the results by the client_ip field.
func ByClientIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientIP, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByInboundEndpoint orders the results by the inbound_endpoint field.
func ByInboundEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInboundEndpoint, opts...).ToFunc()
}

// ByUpstreamEndpoint orders the results by the upstream_endpoint field.
func ByUpstreamEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamEndpoint, opts...).ToFunc()
}
