// Code generated by ent, DO NOT EDIT.

package asyncmediatask

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// InternalRequestID applies equality check predicate on the "internal_request_id" field. It's identical to InternalRequestIDEQ.
func InternalRequestID(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldInternalRequestID, v))
}

// UpstreamRequestID applies equality check predicate on the "upstream_request_id" field. It's identical to UpstreamRequestIDEQ.
func UpstreamRequestID(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// StatusURL applies equality check predicate on the "status_url" field. It's identical to StatusURLEQ.
func StatusURL(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldStatusURL, v))
}

// ResponseURL applies equality check predicate on the "response_url" field. It's identical to ResponseURLEQ.
func ResponseURL(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldResponseURL, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAccountID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUserID, v))
}

// OrganizationID applies equality check predicate on the "organization_id" field. It's identical to OrganizationIDEQ.
func OrganizationID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldOrganizationID, v))
}

// PayerUserID applies equality check predicate on the "payer_user_id" field. It's identical to PayerUserIDEQ.
func PayerUserID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldPayerUserID, v))
}

// BalanceSource applies equality check predicate on the "balance_source" field. It's identical to BalanceSourceEQ.
func BalanceSource(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldBalanceSource, v))
}

// AuthzGeneration applies equality check predicate on the "authz_generation" field. It's identical to AuthzGenerationEQ.
func AuthzGeneration(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAuthzGeneration, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldGroupID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldChannelID, v))
}

// Facade applies equality check predicate on the "facade" field. It's identical to FacadeEQ.
func Facade(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFacade, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldRequestedModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// ImageSize applies equality check predicate on the "image_size" field. It's identical to ImageSizeEQ.
func ImageSize(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldImageSize, v))
}

// Quality applies equality check predicate on the "quality" field. It's identical to QualityEQ.
func Quality(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldQuality, v))
}

// NumImages applies equality check predicate on the "num_images" field. It's identical to NumImagesEQ.
func NumImages(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldNumImages, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldStatus, v))
}

// HeldCost applies equality check predicate on the "held_cost" field. It's identical to HeldCostEQ.
func HeldCost(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldHeldCost, v))
}

// FinalCost applies equality check predicate on the "final_cost" field. It's identical to FinalCostEQ.
func FinalCost(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFinalCost, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldRateMultiplier, v))
}

// SizeTier applies equality check predicate on the "size_tier" field. It's identical to SizeTierEQ.
func SizeTier(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldSizeTier, v))
}

// ErrorReason applies equality check predicate on the "error_reason" field. It's identical to ErrorReasonEQ.
func ErrorReason(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldErrorReason, v))
}

// ErrorCode applies equality check predicate on the "error_code" field. It's identical to ErrorCodeEQ.
func ErrorCode(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldErrorCode, v))
}

// FailDeadlineAt applies equality check predicate on the "fail_deadline_at" field. It's identical to FailDeadlineAtEQ.
func FailDeadlineAt(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFailDeadlineAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFinishedAt, v))
}

// ClientIP applies equality check predicate on the "client_ip" field. It's identical to ClientIPEQ.
func ClientIP(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldClientIP, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUserAgent, v))
}

// InboundEndpoint applies equality check predicate on the "inbound_endpoint" field. It's identical to InboundEndpointEQ.
func InboundEndpoint(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldInboundEndpoint, v))
}

// UpstreamEndpoint applies equality check predicate on the "upstream_endpoint" field. It's identical to UpstreamEndpointEQ.
func UpstreamEndpoint(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUpdatedAt, v))
}

// InternalRequestIDEQ applies the EQ predicate on the "internal_request_id" field.
func InternalRequestIDEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldInternalRequestID, v))
}

// InternalRequestIDNEQ applies the NEQ predicate on the "internal_request_id" field.
func InternalRequestIDNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldInternalRequestID, v))
}

// InternalRequestIDIn applies the In predicate on the "internal_request_id" field.
func InternalRequestIDIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldInternalRequestID, vs...))
}

// InternalRequestIDNotIn applies the NotIn predicate on the "internal_request_id" field.
func InternalRequestIDNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldInternalRequestID, vs...))
}

// InternalRequestIDGT applies the GT predicate on the "internal_request_id" field.
func InternalRequestIDGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldInternalRequestID, v))
}

// InternalRequestIDGTE applies the GTE predicate on the "internal_request_id" field.
func InternalRequestIDGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldInternalRequestID, v))
}

// InternalRequestIDLT applies the LT predicate on the "internal_request_id" field.
func InternalRequestIDLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldInternalRequestID, v))
}

// InternalRequestIDLTE applies the LTE predicate on the "internal_request_id" field.
func InternalRequestIDLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldInternalRequestID, v))
}

// InternalRequestIDContains applies the Contains predicate on the "internal_request_id" field.
func InternalRequestIDContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldInternalRequestID, v))
}

// InternalRequestIDHasPrefix applies the HasPrefix predicate on the "internal_request_id" field.
func InternalRequestIDHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldInternalRequestID, v))
}

// InternalRequestIDHasSuffix applies the HasSuffix predicate on the "internal_request_id" field.
func InternalRequestIDHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldInternalRequestID, v))
}

// InternalRequestIDEqualFold applies the EqualFold predicate on the "internal_request_id" field.
func InternalRequestIDEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldInternalRequestID, v))
}

// InternalRequestIDContainsFold applies the ContainsFold predicate on the "internal_request_id" field.
func InternalRequestIDContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldInternalRequestID, v))
}

// UpstreamRequestIDEQ applies the EQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDNEQ applies the NEQ predicate on the "upstream_request_id" field.
func UpstreamRequestIDNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIn applies the In predicate on the "upstream_request_id" field.
func UpstreamRequestIDIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDNotIn applies the NotIn predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUpstreamRequestID, vs...))
}

// UpstreamRequestIDGT applies the GT predicate on the "upstream_request_id" field.
func UpstreamRequestIDGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDGTE applies the GTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLT applies the LT predicate on the "upstream_request_id" field.
func UpstreamRequestIDLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDLTE applies the LTE predicate on the "upstream_request_id" field.
func UpstreamRequestIDLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContains applies the Contains predicate on the "upstream_request_id" field.
func UpstreamRequestIDContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasPrefix applies the HasPrefix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDHasSuffix applies the HasSuffix predicate on the "upstream_request_id" field.
func UpstreamRequestIDHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDIsNil applies the IsNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDNotNil applies the NotNil predicate on the "upstream_request_id" field.
func UpstreamRequestIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldUpstreamRequestID))
}

// UpstreamRequestIDEqualFold applies the EqualFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldUpstreamRequestID, v))
}

// UpstreamRequestIDContainsFold applies the ContainsFold predicate on the "upstream_request_id" field.
func UpstreamRequestIDContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldUpstreamRequestID, v))
}

// StatusURLEQ applies the EQ predicate on the "status_url" field.
func StatusURLEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldStatusURL, v))
}

// StatusURLNEQ applies the NEQ predicate on the "status_url" field.
func StatusURLNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldStatusURL, v))
}

// StatusURLIn applies the In predicate on the "status_url" field.
func StatusURLIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldStatusURL, vs...))
}

// StatusURLNotIn applies the NotIn predicate on the "status_url" field.
func StatusURLNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldStatusURL, vs...))
}

// StatusURLGT applies the GT predicate on the "status_url" field.
func StatusURLGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldStatusURL, v))
}

// StatusURLGTE applies the GTE predicate on the "status_url" field.
func StatusURLGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldStatusURL, v))
}

// StatusURLLT applies the LT predicate on the "status_url" field.
func StatusURLLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldStatusURL, v))
}

// StatusURLLTE applies the LTE predicate on the "status_url" field.
func StatusURLLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldStatusURL, v))
}

// StatusURLContains applies the Contains predicate on the "status_url" field.
func StatusURLContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldStatusURL, v))
}

// StatusURLHasPrefix applies the HasPrefix predicate on the "status_url" field.
func StatusURLHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldStatusURL, v))
}

// StatusURLHasSuffix applies the HasSuffix predicate on the "status_url" field.
func StatusURLHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldStatusURL, v))
}

// StatusURLIsNil applies the IsNil predicate on the "status_url" field.
func StatusURLIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldStatusURL))
}

// StatusURLNotNil applies the NotNil predicate on the "status_url" field.
func StatusURLNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldStatusURL))
}

// StatusURLEqualFold applies the EqualFold predicate on the "status_url" field.
func StatusURLEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldStatusURL, v))
}

// StatusURLContainsFold applies the ContainsFold predicate on the "status_url" field.
func StatusURLContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldStatusURL, v))
}

// ResponseURLEQ applies the EQ predicate on the "response_url" field.
func ResponseURLEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldResponseURL, v))
}

// ResponseURLNEQ applies the NEQ predicate on the "response_url" field.
func ResponseURLNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldResponseURL, v))
}

// ResponseURLIn applies the In predicate on the "response_url" field.
func ResponseURLIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldResponseURL, vs...))
}

// ResponseURLNotIn applies the NotIn predicate on the "response_url" field.
func ResponseURLNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldResponseURL, vs...))
}

// ResponseURLGT applies the GT predicate on the "response_url" field.
func ResponseURLGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldResponseURL, v))
}

// ResponseURLGTE applies the GTE predicate on the "response_url" field.
func ResponseURLGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldResponseURL, v))
}

// ResponseURLLT applies the LT predicate on the "response_url" field.
func ResponseURLLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldResponseURL, v))
}

// ResponseURLLTE applies the LTE predicate on the "response_url" field.
func ResponseURLLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldResponseURL, v))
}

// ResponseURLContains applies the Contains predicate on the "response_url" field.
func ResponseURLContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldResponseURL, v))
}

// ResponseURLHasPrefix applies the HasPrefix predicate on the "response_url" field.
func ResponseURLHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldResponseURL, v))
}

// ResponseURLHasSuffix applies the HasSuffix predicate on the "response_url" field.
func ResponseURLHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldResponseURL, v))
}

// ResponseURLIsNil applies the IsNil predicate on the "response_url" field.
func ResponseURLIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldResponseURL))
}

// ResponseURLNotNil applies the NotNil predicate on the "response_url" field.
func ResponseURLNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldResponseURL))
}

// ResponseURLEqualFold applies the EqualFold predicate on the "response_url" field.
func ResponseURLEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldResponseURL, v))
}

// ResponseURLContainsFold applies the ContainsFold predicate on the "response_url" field.
func ResponseURLContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldResponseURL, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldAccountID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldAPIKeyID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUserID, v))
}

// OrganizationIDEQ applies the EQ predicate on the "organization_id" field.
func OrganizationIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldOrganizationID, v))
}

// OrganizationIDNEQ applies the NEQ predicate on the "organization_id" field.
func OrganizationIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldOrganizationID, v))
}

// OrganizationIDIn applies the In predicate on the "organization_id" field.
func OrganizationIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldOrganizationID, vs...))
}

// OrganizationIDNotIn applies the NotIn predicate on the "organization_id" field.
func OrganizationIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldOrganizationID, vs...))
}

// OrganizationIDGT applies the GT predicate on the "organization_id" field.
func OrganizationIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldOrganizationID, v))
}

// OrganizationIDGTE applies the GTE predicate on the "organization_id" field.
func OrganizationIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldOrganizationID, v))
}

// OrganizationIDLT applies the LT predicate on the "organization_id" field.
func OrganizationIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldOrganizationID, v))
}

// OrganizationIDLTE applies the LTE predicate on the "organization_id" field.
func OrganizationIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldOrganizationID, v))
}

// OrganizationIDIsNil applies the IsNil predicate on the "organization_id" field.
func OrganizationIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldOrganizationID))
}

// OrganizationIDNotNil applies the NotNil predicate on the "organization_id" field.
func OrganizationIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldOrganizationID))
}

// PayerUserIDEQ applies the EQ predicate on the "payer_user_id" field.
func PayerUserIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldPayerUserID, v))
}

// PayerUserIDNEQ applies the NEQ predicate on the "payer_user_id" field.
func PayerUserIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldPayerUserID, v))
}

// PayerUserIDIn applies the In predicate on the "payer_user_id" field.
func PayerUserIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldPayerUserID, vs...))
}

// PayerUserIDNotIn applies the NotIn predicate on the "payer_user_id" field.
func PayerUserIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldPayerUserID, vs...))
}

// PayerUserIDGT applies the GT predicate on the "payer_user_id" field.
func PayerUserIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldPayerUserID, v))
}

// PayerUserIDGTE applies the GTE predicate on the "payer_user_id" field.
func PayerUserIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldPayerUserID, v))
}

// PayerUserIDLT applies the LT predicate on the "payer_user_id" field.
func PayerUserIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldPayerUserID, v))
}

// PayerUserIDLTE applies the LTE predicate on the "payer_user_id" field.
func PayerUserIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldPayerUserID, v))
}

// PayerUserIDIsNil applies the IsNil predicate on the "payer_user_id" field.
func PayerUserIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldPayerUserID))
}

// PayerUserIDNotNil applies the NotNil predicate on the "payer_user_id" field.
func PayerUserIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldPayerUserID))
}

// BalanceSourceEQ applies the EQ predicate on the "balance_source" field.
func BalanceSourceEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldBalanceSource, v))
}

// BalanceSourceNEQ applies the NEQ predicate on the "balance_source" field.
func BalanceSourceNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldBalanceSource, v))
}

// BalanceSourceIn applies the In predicate on the "balance_source" field.
func BalanceSourceIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldBalanceSource, vs...))
}

// BalanceSourceNotIn applies the NotIn predicate on the "balance_source" field.
func BalanceSourceNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldBalanceSource, vs...))
}

// BalanceSourceGT applies the GT predicate on the "balance_source" field.
func BalanceSourceGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldBalanceSource, v))
}

// BalanceSourceGTE applies the GTE predicate on the "balance_source" field.
func BalanceSourceGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldBalanceSource, v))
}

// BalanceSourceLT applies the LT predicate on the "balance_source" field.
func BalanceSourceLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldBalanceSource, v))
}

// BalanceSourceLTE applies the LTE predicate on the "balance_source" field.
func BalanceSourceLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldBalanceSource, v))
}

// BalanceSourceContains applies the Contains predicate on the "balance_source" field.
func BalanceSourceContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldBalanceSource, v))
}

// BalanceSourceHasPrefix applies the HasPrefix predicate on the "balance_source" field.
func BalanceSourceHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldBalanceSource, v))
}

// BalanceSourceHasSuffix applies the HasSuffix predicate on the "balance_source" field.
func BalanceSourceHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldBalanceSource, v))
}

// BalanceSourceIsNil applies the IsNil predicate on the "balance_source" field.
func BalanceSourceIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldBalanceSource))
}

// BalanceSourceNotNil applies the NotNil predicate on the "balance_source" field.
func BalanceSourceNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldBalanceSource))
}

// BalanceSourceEqualFold applies the EqualFold predicate on the "balance_source" field.
func BalanceSourceEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldBalanceSource, v))
}

// BalanceSourceContainsFold applies the ContainsFold predicate on the "balance_source" field.
func BalanceSourceContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldBalanceSource, v))
}

// AuthzGenerationEQ applies the EQ predicate on the "authz_generation" field.
func AuthzGenerationEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldAuthzGeneration, v))
}

// AuthzGenerationNEQ applies the NEQ predicate on the "authz_generation" field.
func AuthzGenerationNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldAuthzGeneration, v))
}

// AuthzGenerationIn applies the In predicate on the "authz_generation" field.
func AuthzGenerationIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldAuthzGeneration, vs...))
}

// AuthzGenerationNotIn applies the NotIn predicate on the "authz_generation" field.
func AuthzGenerationNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldAuthzGeneration, vs...))
}

// AuthzGenerationGT applies the GT predicate on the "authz_generation" field.
func AuthzGenerationGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldAuthzGeneration, v))
}

// AuthzGenerationGTE applies the GTE predicate on the "authz_generation" field.
func AuthzGenerationGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldAuthzGeneration, v))
}

// AuthzGenerationLT applies the LT predicate on the "authz_generation" field.
func AuthzGenerationLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldAuthzGeneration, v))
}

// AuthzGenerationLTE applies the LTE predicate on the "authz_generation" field.
func AuthzGenerationLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldAuthzGeneration, v))
}

// AuthzGenerationIsNil applies the IsNil predicate on the "authz_generation" field.
func AuthzGenerationIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldAuthzGeneration))
}

// AuthzGenerationNotNil applies the NotNil predicate on the "authz_generation" field.
func AuthzGenerationNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldAuthzGeneration))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldGroupID))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v int64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDIsNil applies the IsNil predicate on the "channel_id" field.
func ChannelIDIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldChannelID))
}

// ChannelIDNotNil applies the NotNil predicate on the "channel_id" field.
func ChannelIDNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldChannelID))
}

// FacadeEQ applies the EQ predicate on the "facade" field.
func FacadeEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFacade, v))
}

// FacadeNEQ applies the NEQ predicate on the "facade" field.
func FacadeNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldFacade, v))
}

// FacadeIn applies the In predicate on the "facade" field.
func FacadeIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldFacade, vs...))
}

// FacadeNotIn applies the NotIn predicate on the "facade" field.
func FacadeNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldFacade, vs...))
}

// FacadeGT applies the GT predicate on the "facade" field.
func FacadeGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldFacade, v))
}

// FacadeGTE applies the GTE predicate on the "facade" field.
func FacadeGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldFacade, v))
}

// FacadeLT applies the LT predicate on the "facade" field.
func FacadeLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldFacade, v))
}

// FacadeLTE applies the LTE predicate on the "facade" field.
func FacadeLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldFacade, v))
}

// FacadeContains applies the Contains predicate on the "facade" field.
func FacadeContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldFacade, v))
}

// FacadeHasPrefix applies the HasPrefix predicate on the "facade" field.
func FacadeHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldFacade, v))
}

// FacadeHasSuffix applies the HasSuffix predicate on the "facade" field.
func FacadeHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldFacade, v))
}

// FacadeEqualFold applies the EqualFold predicate on the "facade" field.
func FacadeEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldFacade, v))
}

// FacadeContainsFold applies the ContainsFold predicate on the "facade" field.
func FacadeContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldFacade, v))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldRequestedModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelIsNil applies the IsNil predicate on the "upstream_model" field.
func UpstreamModelIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldUpstreamModel))
}

// UpstreamModelNotNil applies the NotNil predicate on the "upstream_model" field.
func UpstreamModelNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldUpstreamModel))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// ImageSizeEQ applies the EQ predicate on the "image_size" field.
func ImageSizeEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldImageSize, v))
}

// ImageSizeNEQ applies the NEQ predicate on the "image_size" field.
func ImageSizeNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldImageSize, v))
}

// ImageSizeIn applies the In predicate on the "image_size" field.
func ImageSizeIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldImageSize, vs...))
}

// ImageSizeNotIn applies the NotIn predicate on the "image_size" field.
func ImageSizeNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldImageSize, vs...))
}

// ImageSizeGT applies the GT predicate on the "image_size" field.
func ImageSizeGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldImageSize, v))
}

// ImageSizeGTE applies the GTE predicate on the "image_size" field.
func ImageSizeGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldImageSize, v))
}

// ImageSizeLT applies the LT predicate on the "image_size" field.
func ImageSizeLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldImageSize, v))
}

// ImageSizeLTE applies the LTE predicate on the "image_size" field.
func ImageSizeLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldImageSize, v))
}

// ImageSizeContains applies the Contains predicate on the "image_size" field.
func ImageSizeContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldImageSize, v))
}

// ImageSizeHasPrefix applies the HasPrefix predicate on the "image_size" field.
func ImageSizeHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldImageSize, v))
}

// ImageSizeHasSuffix applies the HasSuffix predicate on the "image_size" field.
func ImageSizeHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldImageSize, v))
}

// ImageSizeIsNil applies the IsNil predicate on the "image_size" field.
func ImageSizeIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldImageSize))
}

// ImageSizeNotNil applies the NotNil predicate on the "image_size" field.
func ImageSizeNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldImageSize))
}

// ImageSizeEqualFold applies the EqualFold predicate on the "image_size" field.
func ImageSizeEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldImageSize, v))
}

// ImageSizeContainsFold applies the ContainsFold predicate on the "image_size" field.
func ImageSizeContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldImageSize, v))
}

// QualityEQ applies the EQ predicate on the "quality" field.
func QualityEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldQuality, v))
}

// QualityNEQ applies the NEQ predicate on the "quality" field.
func QualityNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldQuality, v))
}

// QualityIn applies the In predicate on the "quality" field.
func QualityIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldQuality, vs...))
}

// QualityNotIn applies the NotIn predicate on the "quality" field.
func QualityNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldQuality, vs...))
}

// QualityGT applies the GT predicate on the "quality" field.
func QualityGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldQuality, v))
}

// QualityGTE applies the GTE predicate on the "quality" field.
func QualityGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldQuality, v))
}

// QualityLT applies the LT predicate on the "quality" field.
func QualityLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldQuality, v))
}

// QualityLTE applies the LTE predicate on the "quality" field.
func QualityLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldQuality, v))
}

// QualityContains applies the Contains predicate on the "quality" field.
func QualityContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldQuality, v))
}

// QualityHasPrefix applies the HasPrefix predicate on the "quality" field.
func QualityHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldQuality, v))
}

// QualityHasSuffix applies the HasSuffix predicate on the "quality" field.
func QualityHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldQuality, v))
}

// QualityIsNil applies the IsNil predicate on the "quality" field.
func QualityIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldQuality))
}

// QualityNotNil applies the NotNil predicate on the "quality" field.
func QualityNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldQuality))
}

// QualityEqualFold applies the EqualFold predicate on the "quality" field.
func QualityEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldQuality, v))
}

// QualityContainsFold applies the ContainsFold predicate on the "quality" field.
func QualityContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldQuality, v))
}

// NumImagesEQ applies the EQ predicate on the "num_images" field.
func NumImagesEQ(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldNumImages, v))
}

// NumImagesNEQ applies the NEQ predicate on the "num_images" field.
func NumImagesNEQ(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldNumImages, v))
}

// NumImagesIn applies the In predicate on the "num_images" field.
func NumImagesIn(vs ...int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldNumImages, vs...))
}

// NumImagesNotIn applies the NotIn predicate on the "num_images" field.
func NumImagesNotIn(vs ...int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldNumImages, vs...))
}

// NumImagesGT applies the GT predicate on the "num_images" field.
func NumImagesGT(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldNumImages, v))
}

// NumImagesGTE applies the GTE predicate on the "num_images" field.
func NumImagesGTE(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldNumImages, v))
}

// NumImagesLT applies the LT predicate on the "num_images" field.
func NumImagesLT(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldNumImages, v))
}

// NumImagesLTE applies the LTE predicate on the "num_images" field.
func NumImagesLTE(v int) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldNumImages, v))
}

// RequestParametersIsNil applies the IsNil predicate on the "request_parameters" field.
func RequestParametersIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldRequestParameters))
}

// RequestParametersNotNil applies the NotNil predicate on the "request_parameters" field.
func RequestParametersNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldRequestParameters))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldStatus, v))
}

// HeldCostEQ applies the EQ predicate on the "held_cost" field.
func HeldCostEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldHeldCost, v))
}

// HeldCostNEQ applies the NEQ predicate on the "held_cost" field.
func HeldCostNEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldHeldCost, v))
}

// HeldCostIn applies the In predicate on the "held_cost" field.
func HeldCostIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldHeldCost, vs...))
}

// HeldCostNotIn applies the NotIn predicate on the "held_cost" field.
func HeldCostNotIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldHeldCost, vs...))
}

// HeldCostGT applies the GT predicate on the "held_cost" field.
func HeldCostGT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldHeldCost, v))
}

// HeldCostGTE applies the GTE predicate on the "held_cost" field.
func HeldCostGTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldHeldCost, v))
}

// HeldCostLT applies the LT predicate on the "held_cost" field.
func HeldCostLT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldHeldCost, v))
}

// HeldCostLTE applies the LTE predicate on the "held_cost" field.
func HeldCostLTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldHeldCost, v))
}

// FinalCostEQ applies the EQ predicate on the "final_cost" field.
func FinalCostEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFinalCost, v))
}

// FinalCostNEQ applies the NEQ predicate on the "final_cost" field.
func FinalCostNEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldFinalCost, v))
}

// FinalCostIn applies the In predicate on the "final_cost" field.
func FinalCostIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldFinalCost, vs...))
}

// FinalCostNotIn applies the NotIn predicate on the "final_cost" field.
func FinalCostNotIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldFinalCost, vs...))
}

// FinalCostGT applies the GT predicate on the "final_cost" field.
func FinalCostGT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldFinalCost, v))
}

// FinalCostGTE applies the GTE predicate on the "final_cost" field.
func FinalCostGTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldFinalCost, v))
}

// FinalCostLT applies the LT predicate on the "final_cost" field.
func FinalCostLT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldFinalCost, v))
}

// FinalCostLTE applies the LTE predicate on the "final_cost" field.
func FinalCostLTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldFinalCost, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v float64) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldRateMultiplier, v))
}

// SizeTierEQ applies the EQ predicate on the "size_tier" field.
func SizeTierEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldSizeTier, v))
}

// SizeTierNEQ applies the NEQ predicate on the "size_tier" field.
func SizeTierNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldSizeTier, v))
}

// SizeTierIn applies the In predicate on the "size_tier" field.
func SizeTierIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldSizeTier, vs...))
}

// SizeTierNotIn applies the NotIn predicate on the "size_tier" field.
func SizeTierNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldSizeTier, vs...))
}

// SizeTierGT applies the GT predicate on the "size_tier" field.
func SizeTierGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldSizeTier, v))
}

// SizeTierGTE applies the GTE predicate on the "size_tier" field.
func SizeTierGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldSizeTier, v))
}

// SizeTierLT applies the LT predicate on the "size_tier" field.
func SizeTierLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldSizeTier, v))
}

// SizeTierLTE applies the LTE predicate on the "size_tier" field.
func SizeTierLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldSizeTier, v))
}

// SizeTierContains applies the Contains predicate on the "size_tier" field.
func SizeTierContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldSizeTier, v))
}

// SizeTierHasPrefix applies the HasPrefix predicate on the "size_tier" field.
func SizeTierHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldSizeTier, v))
}

// SizeTierHasSuffix applies the HasSuffix predicate on the "size_tier" field.
func SizeTierHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldSizeTier, v))
}

// SizeTierIsNil applies the IsNil predicate on the "size_tier" field.
func SizeTierIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldSizeTier))
}

// SizeTierNotNil applies the NotNil predicate on the "size_tier" field.
func SizeTierNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldSizeTier))
}

// SizeTierEqualFold applies the EqualFold predicate on the "size_tier" field.
func SizeTierEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldSizeTier, v))
}

// SizeTierContainsFold applies the ContainsFold predicate on the "size_tier" field.
func SizeTierContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldSizeTier, v))
}

// ImageUrlsIsNil applies the IsNil predicate on the "image_urls" field.
func ImageUrlsIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldImageUrls))
}

// ImageUrlsNotNil applies the NotNil predicate on the "image_urls" field.
func ImageUrlsNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldImageUrls))
}

// CosUrlsIsNil applies the IsNil predicate on the "cos_urls" field.
func CosUrlsIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldCosUrls))
}

// CosUrlsNotNil applies the NotNil predicate on the "cos_urls" field.
func CosUrlsNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldCosUrls))
}

// ErrorReasonEQ applies the EQ predicate on the "error_reason" field.
func ErrorReasonEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldErrorReason, v))
}

// ErrorReasonNEQ applies the NEQ predicate on the "error_reason" field.
func ErrorReasonNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldErrorReason, v))
}

// ErrorReasonIn applies the In predicate on the "error_reason" field.
func ErrorReasonIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldErrorReason, vs...))
}

// ErrorReasonNotIn applies the NotIn predicate on the "error_reason" field.
func ErrorReasonNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldErrorReason, vs...))
}

// ErrorReasonGT applies the GT predicate on the "error_reason" field.
func ErrorReasonGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldErrorReason, v))
}

// ErrorReasonGTE applies the GTE predicate on the "error_reason" field.
func ErrorReasonGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldErrorReason, v))
}

// ErrorReasonLT applies the LT predicate on the "error_reason" field.
func ErrorReasonLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldErrorReason, v))
}

// ErrorReasonLTE applies the LTE predicate on the "error_reason" field.
func ErrorReasonLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldErrorReason, v))
}

// ErrorReasonContains applies the Contains predicate on the "error_reason" field.
func ErrorReasonContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldErrorReason, v))
}

// ErrorReasonHasPrefix applies the HasPrefix predicate on the "error_reason" field.
func ErrorReasonHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldErrorReason, v))
}

// ErrorReasonHasSuffix applies the HasSuffix predicate on the "error_reason" field.
func ErrorReasonHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldErrorReason, v))
}

// ErrorReasonIsNil applies the IsNil predicate on the "error_reason" field.
func ErrorReasonIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldErrorReason))
}

// ErrorReasonNotNil applies the NotNil predicate on the "error_reason" field.
func ErrorReasonNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldErrorReason))
}

// ErrorReasonEqualFold applies the EqualFold predicate on the "error_reason" field.
func ErrorReasonEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldErrorReason, v))
}

// ErrorReasonContainsFold applies the ContainsFold predicate on the "error_reason" field.
func ErrorReasonContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldErrorReason, v))
}

// ErrorCodeEQ applies the EQ predicate on the "error_code" field.
func ErrorCodeEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldErrorCode, v))
}

// ErrorCodeNEQ applies the NEQ predicate on the "error_code" field.
func ErrorCodeNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldErrorCode, v))
}

// ErrorCodeIn applies the In predicate on the "error_code" field.
func ErrorCodeIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldErrorCode, vs...))
}

// ErrorCodeNotIn applies the NotIn predicate on the "error_code" field.
func ErrorCodeNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldErrorCode, vs...))
}

// ErrorCodeGT applies the GT predicate on the "error_code" field.
func ErrorCodeGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldErrorCode, v))
}

// ErrorCodeGTE applies the GTE predicate on the "error_code" field.
func ErrorCodeGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldErrorCode, v))
}

// ErrorCodeLT applies the LT predicate on the "error_code" field.
func ErrorCodeLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldErrorCode, v))
}

// ErrorCodeLTE applies the LTE predicate on the "error_code" field.
func ErrorCodeLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldErrorCode, v))
}

// ErrorCodeContains applies the Contains predicate on the "error_code" field.
func ErrorCodeContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldErrorCode, v))
}

// ErrorCodeHasPrefix applies the HasPrefix predicate on the "error_code" field.
func ErrorCodeHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldErrorCode, v))
}

// ErrorCodeHasSuffix applies the HasSuffix predicate on the "error_code" field.
func ErrorCodeHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldErrorCode, v))
}

// ErrorCodeIsNil applies the IsNil predicate on the "error_code" field.
func ErrorCodeIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldErrorCode))
}

// ErrorCodeNotNil applies the NotNil predicate on the "error_code" field.
func ErrorCodeNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldErrorCode))
}

// ErrorCodeEqualFold applies the EqualFold predicate on the "error_code" field.
func ErrorCodeEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldErrorCode, v))
}

// ErrorCodeContainsFold applies the ContainsFold predicate on the "error_code" field.
func ErrorCodeContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldErrorCode, v))
}

// FailDeadlineAtEQ applies the EQ predicate on the "fail_deadline_at" field.
func FailDeadlineAtEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFailDeadlineAt, v))
}

// FailDeadlineAtNEQ applies the NEQ predicate on the "fail_deadline_at" field.
func FailDeadlineAtNEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldFailDeadlineAt, v))
}

// FailDeadlineAtIn applies the In predicate on the "fail_deadline_at" field.
func FailDeadlineAtIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldFailDeadlineAt, vs...))
}

// FailDeadlineAtNotIn applies the NotIn predicate on the "fail_deadline_at" field.
func FailDeadlineAtNotIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldFailDeadlineAt, vs...))
}

// FailDeadlineAtGT applies the GT predicate on the "fail_deadline_at" field.
func FailDeadlineAtGT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldFailDeadlineAt, v))
}

// FailDeadlineAtGTE applies the GTE predicate on the "fail_deadline_at" field.
func FailDeadlineAtGTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldFailDeadlineAt, v))
}

// FailDeadlineAtLT applies the LT predicate on the "fail_deadline_at" field.
func FailDeadlineAtLT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldFailDeadlineAt, v))
}

// FailDeadlineAtLTE applies the LTE predicate on the "fail_deadline_at" field.
func FailDeadlineAtLTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldFailDeadlineAt, v))
}

// FailDeadlineAtIsNil applies the IsNil predicate on the "fail_deadline_at" field.
func FailDeadlineAtIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldFailDeadlineAt))
}

// FailDeadlineAtNotNil applies the NotNil predicate on the "fail_deadline_at" field.
func FailDeadlineAtNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldFailDeadlineAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldFinishedAt))
}

// ClientIPEQ applies the EQ predicate on the "client_ip" field.
func ClientIPEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldClientIP, v))
}

// ClientIPNEQ applies the NEQ predicate on the "client_ip" field.
func ClientIPNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldClientIP, v))
}

// ClientIPIn applies the In predicate on the "client_ip" field.
func ClientIPIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldClientIP, vs...))
}

// ClientIPNotIn applies the NotIn predicate on the "client_ip" field.
func ClientIPNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldClientIP, vs...))
}

// ClientIPGT applies the GT predicate on the "client_ip" field.
func ClientIPGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldClientIP, v))
}

// ClientIPGTE applies the GTE predicate on the "client_ip" field.
func ClientIPGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldClientIP, v))
}

// ClientIPLT applies the LT predicate on the "client_ip" field.
func ClientIPLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldClientIP, v))
}

// ClientIPLTE applies the LTE predicate on the "client_ip" field.
func ClientIPLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldClientIP, v))
}

// ClientIPContains applies the Contains predicate on the "client_ip" field.
func ClientIPContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldClientIP, v))
}

// ClientIPHasPrefix applies the HasPrefix predicate on the "client_ip" field.
func ClientIPHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldClientIP, v))
}

// ClientIPHasSuffix applies the HasSuffix predicate on the "client_ip" field.
func ClientIPHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldClientIP, v))
}

// ClientIPIsNil applies the IsNil predicate on the "client_ip" field.
func ClientIPIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldClientIP))
}

// ClientIPNotNil applies the NotNil predicate on the "client_ip" field.
func ClientIPNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldClientIP))
}

// ClientIPEqualFold applies the EqualFold predicate on the "client_ip" field.
func ClientIPEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldClientIP, v))
}

// ClientIPContainsFold applies the ContainsFold predicate on the "client_ip" field.
func ClientIPContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldClientIP, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentIsNil applies the IsNil predicate on the "user_agent" field.
func UserAgentIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldUserAgent))
}

// UserAgentNotNil applies the NotNil predicate on the "user_agent" field.
func UserAgentNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldUserAgent))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldUserAgent, v))
}

// InboundEndpointEQ applies the EQ predicate on the "inbound_endpoint" field.
func InboundEndpointEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldInboundEndpoint, v))
}

// InboundEndpointNEQ applies the NEQ predicate on the "inbound_endpoint" field.
func InboundEndpointNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldInboundEndpoint, v))
}

// InboundEndpointIn applies the In predicate on the "inbound_endpoint" field.
func InboundEndpointIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointNotIn applies the NotIn predicate on the "inbound_endpoint" field.
func InboundEndpointNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldInboundEndpoint, vs...))
}

// InboundEndpointGT applies the GT predicate on the "inbound_endpoint" field.
func InboundEndpointGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldInboundEndpoint, v))
}

// InboundEndpointGTE applies the GTE predicate on the "inbound_endpoint" field.
func InboundEndpointGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldInboundEndpoint, v))
}

// InboundEndpointLT applies the LT predicate on the "inbound_endpoint" field.
func InboundEndpointLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldInboundEndpoint, v))
}

// InboundEndpointLTE applies the LTE predicate on the "inbound_endpoint" field.
func InboundEndpointLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldInboundEndpoint, v))
}

// InboundEndpointContains applies the Contains predicate on the "inbound_endpoint" field.
func InboundEndpointContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldInboundEndpoint, v))
}

// InboundEndpointHasPrefix applies the HasPrefix predicate on the "inbound_endpoint" field.
func InboundEndpointHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldInboundEndpoint, v))
}

// InboundEndpointHasSuffix applies the HasSuffix predicate on the "inbound_endpoint" field.
func InboundEndpointHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldInboundEndpoint, v))
}

// InboundEndpointIsNil applies the IsNil predicate on the "inbound_endpoint" field.
func InboundEndpointIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldInboundEndpoint))
}

// InboundEndpointNotNil applies the NotNil predicate on the "inbound_endpoint" field.
func InboundEndpointNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldInboundEndpoint))
}

// InboundEndpointEqualFold applies the EqualFold predicate on the "inbound_endpoint" field.
func InboundEndpointEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldInboundEndpoint, v))
}

// InboundEndpointContainsFold applies the ContainsFold predicate on the "inbound_endpoint" field.
func InboundEndpointContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldInboundEndpoint, v))
}

// UpstreamEndpointEQ applies the EQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointNEQ applies the NEQ predicate on the "upstream_endpoint" field.
func UpstreamEndpointNEQ(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNEQ(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIn applies the In predicate on the "upstream_endpoint" field.
func UpstreamEndpointIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointNotIn applies the NotIn predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotIn(vs ...string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotIn(FieldUpstreamEndpoint, vs...))
}

// UpstreamEndpointGT applies the GT predicate on the "upstream_endpoint" field.
func UpstreamEndpointGT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointGTE applies the GTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointGTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldGTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLT applies the LT predicate on the "upstream_endpoint" field.
func UpstreamEndpointLT(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLT(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointLTE applies the LTE predicate on the "upstream_endpoint" field.
func UpstreamEndpointLTE(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldLTE(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContains applies the Contains predicate on the "upstream_endpoint" field.
func UpstreamEndpointContains(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContains(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasPrefix applies the HasPrefix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasPrefix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasPrefix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointHasSuffix applies the HasSuffix predicate on the "upstream_endpoint" field.
func UpstreamEndpointHasSuffix(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldHasSuffix(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointIsNil applies the IsNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointIsNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldIsNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointNotNil applies the NotNil predicate on the "upstream_endpoint" field.
func UpstreamEndpointNotNil() predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldNotNull(FieldUpstreamEndpoint))
}

// UpstreamEndpointEqualFold applies the EqualFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointEqualFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldEqualFold(FieldUpstreamEndpoint, v))
}

// UpstreamEndpointContainsFold applies the ContainsFold predicate on the "upstream_endpoint" field.
func UpstreamEndpointContainsFold(v string) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.FieldContainsFold(FieldUpstreamEndpoint, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AsyncMediaTask) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AsyncMediaTask) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AsyncMediaTask) predicate.AsyncMediaTask {
	return predicate.AsyncMediaTask(sql.NotPredicates(p))
}
